"""FastAPI backend: AppSpec (IR) -> single Python file (app.py).

Reads all data from the fully-resolved AppSpec intermediate representation.
No AST inference is needed -- every name, scope, column mapping, and
reference display column is already resolved in the IR.

Produces functionally equivalent output to the legacy codegen.py.
"""

import json
import re
import textwrap
from datetime import datetime, timezone
from typing import Optional

from ..ir import (
    AppSpec, Table, Column, ColumnType, AccessGrant, Verb,
    StateMachineSpec, TransitionSpec,
    EventSpec, EventConditionSpec, EventActionSpec,
    HttpMethod, RouteKind, RouteSpec,
    PageSpec, TableColumn, FilterField, FormField, HighlightRule,
    RelatedDataSpec, AggregationSpec, ChartSpec,
    NavItemSpec, StreamSpec, RoleSpec, AuthSpec,
    ComputeSpec, ComputeShape, ChannelSpec, ChannelDirection,
    ChannelDelivery, ChannelRequirementSpec, BoundarySpec,
    BoundaryPropertySpec,
)


def _snake(name: str) -> str:
    """Convert a display name to a Python/SQL identifier."""
    return re.sub(r'[^a-z0-9]+', '_', name.lower()).strip('_')


class FastApiBackend:
    """Reference FastAPI backend for the Termin compiler.

    Implements the Backend protocol from termin.backend.
    """

    name = "fastapi"

    def generate(self, spec: AppSpec, source_file: str = "") -> str:
        self.spec = spec
        self.lines: list[str] = []

        # Build lookup helpers from the IR
        self._table_by_snake: dict[str, Table] = {
            t.name.snake: t for t in spec.tables
        }
        self._sm_by_table: dict[str, StateMachineSpec] = {
            sm.table: sm for sm in spec.state_machines
        }
        self._grants_by_table: dict[str, list[AccessGrant]] = {}
        for g in spec.access_grants:
            self._grants_by_table.setdefault(g.table, []).append(g)

        self._emit_header(source_file)
        self._emit_imports()
        self._emit_expression_evaluator()
        self._emit_error_router()
        self._emit_app_setup()
        self._emit_database()
        self._emit_identity()
        self._emit_boundaries()
        self._emit_event_bus()
        self._emit_models()
        self._emit_state_machines()
        self._emit_event_handlers()
        self._emit_api_routes()
        self._emit_compute_routes()
        self._emit_compute_registrations()
        self._emit_channel_endpoints()
        self._emit_reflection_endpoint()
        self._emit_error_log_endpoint()
        self._emit_events_endpoint()
        self._emit_sse_stream()
        self._emit_templates()
        self._emit_page_routes()
        self._emit_startup()
        self._emit_main()
        return "\n".join(self.lines)

    def required_dependencies(self) -> list[str]:
        return [
            "fastapi>=0.100.0",
            "uvicorn>=0.23.0",
            "aiosqlite>=0.19.0",
            "jinja2>=3.1.0",
            "python-multipart>=0.0.6",
            "pyjexl>=0.3.0",
        ]

    # ── Helpers ──

    def _w(self, text: str = "") -> None:
        self.lines.append(text)

    def _wblock(self, text: str) -> None:
        self.lines.append(textwrap.dedent(text))

    def _scope_for_verb(self, table: str, verb: Verb) -> Optional[str]:
        for g in self._grants_by_table.get(table, []):
            if verb in g.verbs:
                return g.scope
        return None

    # ── Header ──

    def _emit_header(self, source_file: str) -> None:
        now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        name = self.spec.name
        self._wblock(f'''\
            # ============================================================
            # GENERATED BY TERMIN COMPILER v0.1
            # Source: {source_file}
            # Generated: {now}
            # Application: {name}
            # DO NOT EDIT -- regenerate from .termin source
            # ============================================================
        ''')

    # ── Imports ──

    def _emit_imports(self) -> None:
        self._wblock('''\
            import asyncio
            import json
            import os
            import sqlite3
            from contextlib import asynccontextmanager
            from datetime import datetime
            from pathlib import Path
            from typing import Optional

            import aiosqlite
            import uvicorn
            from fastapi import FastAPI, Request, Response, HTTPException, Depends, Form, Query, WebSocket
            from fastapi.responses import HTMLResponse, RedirectResponse, StreamingResponse
            from jinja2 import Environment, BaseLoader
            from pydantic import BaseModel, field_validator
        ''')

    # ── Expression Evaluator ──

    def _emit_expression_evaluator(self) -> None:
        self._wblock('''\
            from pyjexl import JEXL

            class ExpressionEvaluator:
                def __init__(self):
                    self.jexl = JEXL()
                    self._functions = {}

                def register_function(self, name, fn):
                    self._functions[name] = fn

                def evaluate(self, expression, context=None):
                    ctx = context or {}
                    for name, fn in self._functions.items():
                        ctx[name] = fn
                    return self.jexl.evaluate(expression, ctx)

            expr_eval = ExpressionEvaluator()
        ''')

    # ── Error Router (TerminAtor) ──

    def _emit_error_router(self) -> None:
        self._wblock('''\
            class TerminError:
                def __init__(self, source, kind, message, context=None, boundary_path=None):
                    self.source = source
                    self.kind = kind  # validation, authorization, state, timeout, schema, internal, external
                    self.message = message
                    self.timestamp = datetime.now().isoformat()
                    self.context = context or ""
                    self.boundary_path = boundary_path or []

            class TerminAtor:
                def __init__(self):
                    self._handlers = {}
                    self._error_log = []

                def route(self, error: TerminError):
                    self._error_log.append(error.__dict__)
                    # Try boundary-specific handler
                    for boundary in error.boundary_path:
                        if boundary in self._handlers:
                            self._handlers[boundary](error)
                            return
                    # Global fallback
                    print(f"[TerminAtor] {error.kind}: {error.message} (from {error.source})")

                def register_handler(self, boundary, handler):
                    self._handlers[boundary] = handler

                def get_error_log(self):
                    return self._error_log

            terminator = TerminAtor()
        ''')

    # ── App Setup ──

    def _emit_app_setup(self) -> None:
        name = self.spec.name
        desc = self.spec.description
        self._w(f'DB_PATH = "app.db"')
        self._w()
        self._w(f'app = FastAPI(title="{name}", description="{desc}")')
        self._w()

    # ── Database ──

    def _emit_database(self) -> None:
        self._wblock('''\
            async def get_db():
                db = await aiosqlite.connect(DB_PATH)
                db.row_factory = aiosqlite.Row
                await db.execute("PRAGMA foreign_keys = ON")
                return db

            async def init_db():
                db = await get_db()
                try:
        ''')

        for table in self.spec.tables:
            tname = table.name.snake
            cols = ["id INTEGER PRIMARY KEY AUTOINCREMENT"]

            # Status column from state machine
            if table.has_status_column and table.initial_status:
                cols.append(f"status TEXT NOT NULL DEFAULT '{table.initial_status}'")

            for col in table.columns:
                col_def = self._sql_column_def(col)
                cols.append(col_def)

            # Foreign key clauses
            fk_clauses = []
            for col in table.columns:
                if col.foreign_key:
                    fk_clauses.append(
                        f"FOREIGN KEY ({col.name}) REFERENCES {col.foreign_key}(id)"
                    )

            all_cols = cols + fk_clauses
            cols_sql = ",\n                ".join(all_cols)
            self._w(f'        await db.execute("""')
            self._w(f"            CREATE TABLE IF NOT EXISTS {tname} (")
            self._w(f"                {cols_sql}")
            self._w(f"            )")
            self._w(f'        """)')
            self._w()

        self._w("        await db.commit()")
        self._w("    finally:")
        self._w("        await db.close()")
        self._w()

    def _sql_column_def(self, col: Column) -> str:
        """Build a SQL column definition from an IR Column."""
        parts: list[str] = []

        if col.is_auto:
            parts.append("TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
        elif col.enum_values:
            vals = ", ".join(f"'{v}'" for v in col.enum_values)
            parts.append(f"TEXT CHECK({col.name} IN ({vals}))")
        elif col.column_type == ColumnType.TEXT:
            parts.append("TEXT")
        elif col.column_type == ColumnType.INTEGER:
            parts.append("INTEGER")
        elif col.column_type == ColumnType.REAL:
            parts.append("REAL")
        elif col.column_type == ColumnType.BOOLEAN:
            parts.append("INTEGER")  # SQLite: 0/1
        elif col.column_type == ColumnType.DATE:
            parts.append("TEXT")     # ISO date string
        elif col.column_type == ColumnType.TIMESTAMP:
            parts.append("TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
        elif col.column_type == ColumnType.JSON:
            parts.append("TEXT")     # JSON string
        else:
            parts.append("TEXT")

        if col.required:
            parts.append("NOT NULL")
        if col.unique:
            parts.append("UNIQUE")
        if col.minimum is not None and col.maximum is not None:
            parts.append(f"CHECK({col.name} >= {col.minimum} AND {col.name} <= {col.maximum})")
        elif col.minimum is not None:
            parts.append(f"CHECK({col.name} >= {col.minimum})")
        elif col.maximum is not None:
            parts.append(f"CHECK({col.name} <= {col.maximum})")

        return f"{col.name} {' '.join(parts)}"

    # ── Identity / Auth ──

    def _emit_identity(self) -> None:
        roles_dict = {}
        for role in self.spec.auth.roles:
            roles_dict[role.name] = list(role.scopes)
        # Anonymous is always available as a built-in role (listed last so real roles are default)
        if not any(k.lower() == "anonymous" for k in roles_dict):
            roles_dict["anonymous"] = []

        self._w(f"ROLES = {repr(roles_dict)}")
        self._w()

        scopes = list(self.spec.auth.scopes)
        self._w(f"ALL_SCOPES = {repr(scopes)}")
        self._w()

        self._wblock('''\
            def get_current_user(request: Request) -> dict:
                """Get current user from cookie or default to first role."""
                role = request.cookies.get("termin_role", list(ROLES.keys())[0])
                if role not in ROLES:
                    role = list(ROLES.keys())[0]
                display_name = request.cookies.get("termin_user_name", "User")
                profile = {"FirstName": display_name, "DisplayName": display_name}
                if role == "anonymous":
                    profile = {"FirstName": "Anonymous", "DisplayName": "Anonymous"}
                return {"role": role, "scopes": ROLES[role], "profile": profile}

            def require_scope(scope: str):
                """FastAPI dependency that checks the user has a required scope."""
                def checker(request: Request):
                    user = get_current_user(request)
                    if scope not in user["scopes"]:
                        raise HTTPException(status_code=403, detail=f"Requires scope: {scope}")
                    return user
                return checker
        ''')

    # ── Boundaries ──

    def _emit_boundaries(self) -> None:
        if not self.spec.boundaries:
            return
        self._w()
        self._w("# ── Boundary Definitions ──")
        self._w()
        self._w("BOUNDARIES = {")
        for bnd in self.spec.boundaries:
            tables = ", ".join(f'"{t}"' for t in bnd.contains_tables)
            sub = ", ".join(f'"{b}"' for b in bnd.contains_boundaries)
            self._w(f'    "{bnd.name.snake}": {{')
            self._w(f'        "tables": [{tables}],')
            self._w(f'        "sub_boundaries": [{sub}],')
            self._w(f'        "identity_mode": "{bnd.identity_mode}",')
            if bnd.identity_scopes:
                scopes = ", ".join(f'"{s}"' for s in bnd.identity_scopes)
                self._w(f'        "restrict_scopes": [{scopes}],')
            self._w(f'    }},')
        self._w("}")
        self._w()

        # Generate scope enforcement for restricted boundaries
        for bnd in self.spec.boundaries:
            if bnd.identity_mode == "restrict" and bnd.identity_scopes:
                snake = bnd.name.snake
                scopes = bnd.identity_scopes
                self._w(f'def require_boundary_{snake}(user=Depends(get_current_user)):')
                self._w(f'    """Enforce scope restriction for boundary: {bnd.name.display}"""')
                for scope in scopes:
                    self._w(f'    if "{scope}" not in user["scopes"]:')
                    self._w(f'        raise HTTPException(status_code=403, detail="Boundary {bnd.name.display} requires scope: {scope}")')
                self._w(f'    return user')
                self._w()

    # ── Event Bus ──

    def _emit_event_bus(self) -> None:
        self._wblock('''\
            class EventBus:
                def __init__(self):
                    self._subscribers: list[asyncio.Queue] = []
                    self._event_log: list[dict] = []

                def subscribe(self) -> asyncio.Queue:
                    q: asyncio.Queue = asyncio.Queue()
                    self._subscribers.append(q)
                    return q

                def unsubscribe(self, q: asyncio.Queue):
                    self._subscribers.remove(q)

                async def publish(self, event: dict):
                    event.setdefault("log_level", "INFO")
                    event.setdefault("timestamp", datetime.now().isoformat())
                    self._event_log.append(event)
                    # Keep only last 1000 events
                    if len(self._event_log) > 1000:
                        self._event_log = self._event_log[-1000:]
                    for q in self._subscribers:
                        await q.put(event)

                def get_event_log(self):
                    return list(self._event_log)

            event_bus = EventBus()
        ''')

    # ── Pydantic Models ──

    def _emit_models(self) -> None:
        for table in self.spec.tables:
            class_name = table.name.pascal
            self._w(f"class {class_name}Create(BaseModel):")
            has_fields = False
            for col in table.columns:
                if col.is_auto:
                    continue
                ptype = self._pydantic_type(col)
                default = "" if col.required else " = None"
                self._w(f"    {col.name}: {ptype}{default}")
                has_fields = True
            if not has_fields:
                self._w("    pass")

            # Validators for enum fields
            for col in table.columns:
                if col.enum_values:
                    vals = repr(col.enum_values)
                    self._w()
                    self._w(f'    @field_validator("{col.name}")')
                    self._w(f"    @classmethod")
                    self._w(f"    def validate_{col.name}(cls, v):")
                    self._w(f"        if v is not None and v not in {vals}:")
                    self._w(f'            raise ValueError(f"{{v}} is not a valid {col.display_name}")')
                    self._w(f"        return v")

            self._w()

            # Update model (all optional)
            self._w(f"class {class_name}Update(BaseModel):")
            has_upd_fields = False
            for col in table.columns:
                if col.is_auto:
                    continue
                ptype = self._pydantic_type_optional(col)
                self._w(f"    {col.name}: {ptype} = None")
                has_upd_fields = True
            if not has_upd_fields:
                self._w("    pass")
            self._w()

    def _pydantic_type(self, col: Column) -> str:
        if col.column_type == ColumnType.INTEGER:
            base = "int"
        elif col.column_type == ColumnType.REAL:
            base = "float"
        else:
            base = "str"
        if not col.required:
            return f"Optional[{base}]"
        return base

    def _pydantic_type_optional(self, col: Column) -> str:
        base = self._pydantic_type(col)
        if base.startswith("Optional["):
            return base
        return f"Optional[{base}]"

    # ── State Machines ──

    def _emit_state_machines(self) -> None:
        if not self.spec.state_machines:
            return

        self._w("# --- State Machine Transition Tables ---")
        self._w()
        self._w("STATE_MACHINES = {")
        for sm in self.spec.state_machines:
            self._w(f'    "{sm.table}": {{')
            self._w(f'        "initial": "{sm.initial_state}",')
            self._w(f'        "transitions": {{')
            for tr in sm.transitions:
                self._w(f'            ("{tr.from_state}", "{tr.to_state}"): "{tr.required_scope}",')
            self._w(f'        }},')
            self._w(f'    }},')
        self._w("}")
        self._w()

        self._wblock('''\
            async def do_state_transition(db, table: str, record_id: int, target_state: str, user: dict):
                """Attempt a state transition. Raises HTTPException on invalid transition."""
                if table not in STATE_MACHINES:
                    raise HTTPException(status_code=400, detail=f"No state machine for {table}")

                sm = STATE_MACHINES[table]
                cursor = await db.execute(f"SELECT status FROM {table} WHERE id = ?", (record_id,))
                row = await cursor.fetchone()
                if not row:
                    raise HTTPException(status_code=404, detail="Record not found")

                current = row["status"]
                key = (current, target_state)
                if key not in sm["transitions"]:
                    terminator.route(TerminError(
                        source=f"state:{table}",
                        kind="state",
                        message=f"Cannot transition from '{current}' to '{target_state}'",
                        context=f"record_id={record_id}",
                    ))
                    raise HTTPException(
                        status_code=409,
                        detail=f"Cannot transition from '{current}' to '{target_state}'"
                    )

                required_scope = sm["transitions"][key]
                if required_scope not in user["scopes"]:
                    terminator.route(TerminError(
                        source=f"state:{table}",
                        kind="authorization",
                        message=f"Transition requires scope: {required_scope}",
                        context=f"record_id={record_id}, user_role={user.get('role', '')}",
                    ))
                    raise HTTPException(
                        status_code=403,
                        detail=f"Transition requires scope: {required_scope}"
                    )

                await db.execute(f"UPDATE {table} SET status = ? WHERE id = ?", (target_state, record_id))
                await db.commit()
                await event_bus.publish({"type": f"{table}_updated", "id": record_id, "status": target_state})
                return {"id": record_id, "status": target_state}
        ''')

    # ── Event Handlers ──

    def _emit_event_handlers(self) -> None:
        if not self.spec.events:
            self._w("async def run_event_handlers(db, content_name: str, trigger: str, record: dict):")
            self._w("    pass")
            self._w()
            return

        self._w("async def run_event_handlers(db, content_name: str, trigger: str, record: dict):")
        self._w('    """Execute event rules that match the content mutation."""')

        for ev in self.spec.events:
            # JEXL-triggered events use expression evaluation
            if ev.trigger == "jexl" and ev.jexl_condition:
                jexl_expr = ev.jexl_condition.replace("'", "\\'")
                self._w(f'    if content_name == "{ev.source_table}":')
                self._w(f"        if expr_eval.evaluate('{jexl_expr}', record):")
            elif ev.condition:
                self._w(f'    if content_name == "{ev.source_table}" and trigger == "{ev.trigger}":')
                left = ev.condition.left_column
                right = ev.condition.right_column
                if ev.condition.operator == "lte":
                    self._w(f'        if record.get("{left}", 0) <= record.get("{right}", 0):')
                else:
                    self._w(f'        if True:  # condition: {ev.condition.operator}')
            else:
                self._w(f'    if content_name == "{ev.source_table}" and trigger == "{ev.trigger}":')

            log_level = ev.log_level
            if ev.action and ev.action.column_mapping:
                target_table = ev.action.target_table
                target_cols = [pair[0] for pair in ev.action.column_mapping]
                source_keys = [pair[1] for pair in ev.action.column_mapping]

                cols = ", ".join(target_cols)
                placeholders = ", ".join(["?"] * len(target_cols))
                values = ", ".join(f'record.get("{sk}", "")' for sk in source_keys)

                self._w(f'            await db.execute(')
                self._w(f'                "INSERT INTO {target_table} ({cols}) VALUES ({placeholders})",')
                self._w(f'                ({values},)')
                self._w(f'            )')
                self._w(f'            await db.commit()')
                self._w(f'            await event_bus.publish({{"type": "{target_table}_created", "log_level": "{log_level}"}})')
            elif ev.action:
                # Action with no column mapping — emit event only
                self._w(f'            await event_bus.publish({{"type": "{ev.action.target_table}_created", "data": record, "log_level": "{log_level}"}})')
            else:
                self._w(f'        pass  # No action defined for this event')

        self._w()

    # ── API Routes ──

    def _emit_api_routes(self) -> None:
        if not self.spec.routes:
            return

        for route in self.spec.routes:
            if route.kind == RouteKind.STREAM:
                continue  # handled separately in _emit_sse_stream

            table = route.table
            method = route.method.value.lower()
            path = route.path

            if route.kind == RouteKind.TRANSITION:
                self._emit_transition_route(route)
            elif route.kind == RouteKind.LIST:
                self._emit_list_route(route)
            elif route.kind == RouteKind.GET_ONE:
                self._emit_get_route(route)
            elif route.kind == RouteKind.CREATE:
                self._emit_create_route(route)
            elif route.kind == RouteKind.UPDATE:
                self._emit_update_route(route)
            elif route.kind == RouteKind.DELETE:
                self._emit_delete_route(route)

    def _emit_list_route(self, route: RouteSpec) -> None:
        scope = route.required_scope
        scope_dep = f', user=Depends(require_scope("{scope}"))' if scope else ""
        table = route.table
        self._w(f'@app.get("{route.path}")')
        self._w(f"async def list_{table}(request: Request{scope_dep}):")
        self._w(f'    db = await get_db()')
        self._w(f'    try:')
        self._w(f'        cursor = await db.execute("SELECT * FROM {table}")')
        self._w(f'        rows = await cursor.fetchall()')
        self._w(f'        return [{{"id": r["id"], **dict(r)}} for r in rows]')
        self._w(f'    finally:')
        self._w(f'        await db.close()')
        self._w()

    def _emit_get_route(self, route: RouteSpec) -> None:
        scope = route.required_scope
        scope_dep = f', user=Depends(require_scope("{scope}"))' if scope else ""
        table = route.table
        param = re.search(r'\{(\w+)\}', route.path)
        param_name = param.group(1) if param else "id"
        lookup_col = route.lookup_column

        self._w(f'@app.get("{route.path}")')
        self._w(f"async def get_{table}_by_{param_name}({param_name}: str{scope_dep}):")
        self._w(f'    db = await get_db()')
        self._w(f'    try:')
        self._w(f'        cursor = await db.execute("SELECT * FROM {table} WHERE {lookup_col} = ?", ({param_name},))')
        self._w(f'        row = await cursor.fetchone()')
        self._w(f'        if not row:')
        self._w(f'            raise HTTPException(status_code=404, detail="Not found")')
        self._w(f'        return dict(row)')
        self._w(f'    finally:')
        self._w(f'        await db.close()')
        self._w()

    def _emit_create_route(self, route: RouteSpec) -> None:
        scope = route.required_scope
        scope_dep = f', user=Depends(require_scope("{scope}"))' if scope else ""
        table_obj = self._table_by_snake.get(route.table)
        table = route.table
        model_name = table_obj.name.pascal + "Create" if table_obj else _snake(table).title().replace("_", "") + "Create"

        self._w(f'@app.post("{route.path}", status_code=201)')
        self._w(f"async def create_{table}(data: {model_name}{scope_dep}):")
        self._w(f'    db = await get_db()')
        self._w(f'    try:')
        self._w(f'        d = data.model_dump(exclude_none=True)')

        # Add initial state if state machine exists
        sm = self._sm_by_table.get(table)
        if sm:
            self._w(f'        d.setdefault("status", "{sm.initial_state}")')

        self._w(f'        columns = [k for k in d.keys()]')
        self._w(f'        placeholders = ", ".join(["?"] * len(columns))')
        self._w(f'        col_str = ", ".join(columns)')
        self._w(f'        values = [d[k] for k in columns]')
        self._w(f'        try:')
        self._w(f'            cursor = await db.execute(f"INSERT INTO {table} ({{col_str}}) VALUES ({{placeholders}})", values)')
        self._w(f'        except sqlite3.IntegrityError as e:')
        self._w(f'            terminator.route(TerminError(')
        self._w(f'                source="content:{table}",')
        self._w(f'                kind="validation",')
        self._w(f'                message=str(e),')
        self._w(f'                context=f"create {{d}}",')
        self._w(f'            ))')
        self._w(f'            raise HTTPException(status_code=409, detail=str(e))')
        self._w(f'        await db.commit()')
        self._w(f'        record_id = cursor.lastrowid')

        # Fetch created record for event handlers
        self._w(f'        cursor2 = await db.execute("SELECT * FROM {table} WHERE id = ?", (record_id,))')
        self._w(f'        record = dict(await cursor2.fetchone())')
        self._w(f'        await run_event_handlers(db, "{table}", "created", record)')
        self._w(f'        await event_bus.publish({{"type": "{table}_created", "id": record_id}})')
        self._w(f'        return {{"id": record_id, **record}}')
        self._w(f'    finally:')
        self._w(f'        await db.close()')
        self._w()

    def _emit_update_route(self, route: RouteSpec) -> None:
        scope = route.required_scope
        scope_dep = f', user=Depends(require_scope("{scope}"))' if scope else ""
        table_obj = self._table_by_snake.get(route.table)
        table = route.table
        model_name = table_obj.name.pascal + "Update" if table_obj else _snake(table).title().replace("_", "") + "Update"
        param = re.search(r'\{(\w+)\}', route.path)
        param_name = param.group(1) if param else "id"
        lookup_col = route.lookup_column

        self._w(f'@app.put("{route.path}")')
        self._w(f"async def update_{table}({param_name}: str, data: {model_name}{scope_dep}):")
        self._w(f'    db = await get_db()')
        self._w(f'    try:')
        self._w(f'        d = data.model_dump(exclude_unset=True)')
        self._w(f'        if not d:')
        self._w(f'            terminator.route(TerminError(')
        self._w(f'                source="content:{table}",')
        self._w(f'                kind="validation",')
        self._w(f'                message="No fields to update",')
        self._w(f'            ))')
        self._w(f'            raise HTTPException(status_code=422, detail="No fields to update")')
        self._w(f'        set_clause = ", ".join(f"{{k}} = ?" for k in d.keys())')
        self._w(f'        values = list(d.values()) + [{param_name}]')
        self._w(f'        await db.execute(f"UPDATE {table} SET {{set_clause}} WHERE {lookup_col} = ?", values)')
        self._w(f'        await db.commit()')

        # Fetch updated record for event handlers
        self._w(f'        cursor = await db.execute("SELECT * FROM {table} WHERE {lookup_col} = ?", ({param_name},))')
        self._w(f'        row = await cursor.fetchone()')
        self._w(f'        if not row:')
        self._w(f'            raise HTTPException(status_code=404, detail="Not found")')
        self._w(f'        record = dict(row)')
        self._w(f'        await run_event_handlers(db, "{table}", "updated", record)')
        self._w(f'        await event_bus.publish({{"type": "{table}_updated", "id": row["id"]}})')
        self._w(f'        return record')
        self._w(f'    finally:')
        self._w(f'        await db.close()')
        self._w()

    def _emit_delete_route(self, route: RouteSpec) -> None:
        scope = route.required_scope
        scope_dep = f', user=Depends(require_scope("{scope}"))' if scope else ""
        table = route.table
        param = re.search(r'\{(\w+)\}', route.path)
        param_name = param.group(1) if param else "id"
        lookup_col = route.lookup_column

        self._w(f'@app.delete("{route.path}")')
        self._w(f"async def delete_{table}({param_name}: str{scope_dep}):")
        self._w(f'    db = await get_db()')
        self._w(f'    try:')
        self._w(f'        cursor = await db.execute("SELECT * FROM {table} WHERE {lookup_col} = ?", ({param_name},))')
        self._w(f'        row = await cursor.fetchone()')
        self._w(f'        if not row:')
        self._w(f'            raise HTTPException(status_code=404, detail="Not found")')
        self._w(f'        await db.execute("DELETE FROM {table} WHERE {lookup_col} = ?", ({param_name},))')
        self._w(f'        await db.commit()')
        self._w(f'        await event_bus.publish({{"type": "{table}_deleted", "id": row["id"]}})')
        self._w(f'        return {{"deleted": True}}')
        self._w(f'    finally:')
        self._w(f'        await db.close()')
        self._w()

    def _emit_transition_route(self, route: RouteSpec) -> None:
        table = route.table
        method = route.method.value.lower()
        path = route.path
        target_state = route.target_state or ""
        lookup_col = route.lookup_column

        parts = path.rstrip("/").split("/")
        action = parts[-1]
        route_name = f"transition_{table}_{_snake(action)}"

        param = re.search(r'\{(\w+)\}', path)
        param_name = param.group(1) if param else "id"

        self._w(f'@app.{method}("{path}")')
        self._w(f"async def {route_name}({param_name}: str, user=Depends(get_current_user)):")
        self._w(f'    db = await get_db()')
        self._w(f'    try:')
        self._w(f'        cursor = await db.execute("SELECT id, status FROM {table} WHERE {lookup_col} = ?", ({param_name},))')
        self._w(f'        row = await cursor.fetchone()')
        self._w(f'        if not row:')
        self._w(f'            raise HTTPException(status_code=404, detail="Not found")')
        self._w(f'        return await do_state_transition(db, "{table}", row["id"], "{target_state}", user)')
        self._w(f'    finally:')
        self._w(f'        await db.close()')
        self._w()

    # ── Compute Routes ──

    def _emit_compute_routes(self) -> None:
        if not self.spec.computes:
            return

        self._w()
        self._w("# ── Compute Endpoints ──")
        self._w()

        for comp in self.spec.computes:
            snake = comp.name.snake
            scope = comp.required_scope
            scope_dep = f', user=Depends(require_scope("{scope}"))' if scope else ""

            if comp.shape == ComputeShape.TRANSFORM:
                self._emit_compute_transform(comp, snake, scope_dep)
            elif comp.shape == ComputeShape.REDUCE:
                self._emit_compute_reduce(comp, snake, scope_dep)
            elif comp.shape == ComputeShape.EXPAND:
                self._emit_compute_expand(comp, snake, scope_dep)
            elif comp.shape == ComputeShape.CORRELATE:
                self._emit_compute_correlate(comp, snake, scope_dep)
            elif comp.shape == ComputeShape.ROUTE:
                self._emit_compute_route(comp, snake, scope_dep)

    def _emit_compute_transform(self, comp: ComputeSpec, snake: str, scope_dep: str) -> None:
        input_table = comp.input_tables[0] if comp.input_tables else "unknown"
        self._w(f'@app.post("/compute/{snake}")')
        self._w(f"async def compute_{snake}(request: Request{scope_dep}):")
        self._w(f"    body = await request.json()")
        if comp.body_lines:
            # Use the first body line as a JEXL expression to evaluate
            expr = comp.body_lines[0].replace("'", "\\'")
            for line in comp.body_lines:
                self._w(f"    # {line}")
            self._w(f"    try:")
            self._w(f"        result = expr_eval.evaluate('{expr}', {{'input': body}})")
            self._w(f"        return result")
            self._w(f"    except Exception as e:")
            self._w(f"        terminator.route(TerminError(")
            self._w(f'            source="compute:{snake}",')
            self._w(f'            kind="internal",')
            self._w(f"            message=str(e),")
            self._w(f"        ))")
            self._w(f"        return body  # Expression evaluation failed, return input")
        else:
            self._w(f"    # Input from: {input_table}")
            self._w(f"    return body  # No body expression defined")
        self._w()

    def _emit_compute_reduce(self, comp: ComputeSpec, snake: str, scope_dep: str) -> None:
        input_table = comp.input_tables[0] if comp.input_tables else "unknown"
        self._w(f'@app.post("/compute/{snake}")')
        self._w(f"async def compute_{snake}(request: Request{scope_dep}):")
        self._w(f'    # Reduce: {" / ".join(comp.body_lines) if comp.body_lines else "N records in, 1 summary out"}')
        self._w(f"    db = await get_db()")
        self._w(f"    try:")
        self._w(f'        cursor = await db.execute("SELECT * FROM {input_table}")')
        self._w(f"        rows = await cursor.fetchall()")
        self._w(f"        result = {{")
        self._w(f'            "count": len(rows),')
        self._w(f'            "source_table": "{input_table}",')
        self._w(f"        }}")
        self._w(f"        return result")
        self._w(f"    finally:")
        self._w(f"        await db.close()")
        self._w()

    def _emit_compute_expand(self, comp: ComputeSpec, snake: str, scope_dep: str) -> None:
        self._w(f'@app.post("/compute/{snake}")')
        self._w(f"async def compute_{snake}(request: Request{scope_dep}):")
        self._w(f"    body = await request.json()")
        self._w(f'    # Expand: {" / ".join(comp.body_lines) if comp.body_lines else "1 record in, N records out"}')
        self._w(f"    return [body]  # TODO: expand into multiple records")
        self._w()

    def _emit_compute_correlate(self, comp: ComputeSpec, snake: str, scope_dep: str) -> None:
        tables = comp.input_tables
        t1 = tables[0] if len(tables) > 0 else "table_a"
        t2 = tables[1] if len(tables) > 1 else "table_b"
        self._w(f'@app.post("/compute/{snake}")')
        self._w(f"async def compute_{snake}(request: Request{scope_dep}):")
        self._w(f'    # Correlate: {" / ".join(comp.body_lines) if comp.body_lines else f"join {t1} and {t2}"}')
        self._w(f"    db = await get_db()")
        self._w(f"    try:")
        self._w(f'        c1 = await db.execute("SELECT * FROM {t1}")')
        self._w(f"        rows1 = await c1.fetchall()")
        self._w(f'        c2 = await db.execute("SELECT * FROM {t2}")')
        self._w(f"        rows2 = await c2.fetchall()")
        self._w(f"        return {{")
        self._w(f'            "{t1}": [dict(r) for r in rows1],')
        self._w(f'            "{t2}": [dict(r) for r in rows2],')
        self._w(f'            "matched": [],  # TODO: apply correlation logic')
        self._w(f"        }}")
        self._w(f"    finally:")
        self._w(f"        await db.close()")
        self._w()

    def _emit_compute_route(self, comp: ComputeSpec, snake: str, scope_dep: str) -> None:
        outputs = comp.output_tables
        self._w(f'@app.post("/compute/{snake}")')
        self._w(f"async def compute_{snake}(request: Request{scope_dep}):")
        self._w(f"    body = await request.json()")
        self._w(f'    # Route: classify input into one of {outputs}')
        self._w(f'    return {{"input": body, "routed_to": "{outputs[0] if outputs else "unknown"}"}}  # TODO: apply routing logic')
        self._w()

    # ── Compute Registrations ──

    def _emit_compute_registrations(self) -> None:
        """Register each Compute as a callable function in the expression evaluator."""
        if not self.spec.computes:
            return

        self._w()
        self._w("# ── Register Compute Functions with Expression Evaluator ──")
        self._w()

        for comp in self.spec.computes:
            snake = comp.name.snake
            display = comp.name.display
            # Register a sync wrapper that calls the compute endpoint logic
            self._w(f"def _compute_fn_{snake}(input_data):")
            if comp.body_lines:
                expr = comp.body_lines[0].replace("'", "\\'")
                self._w(f"    try:")
                self._w(f"        return expr_eval.evaluate('{expr}', {{'input': input_data}})")
                self._w(f"    except Exception:")
                self._w(f"        return input_data  # Expression evaluation failed")
            else:
                self._w(f"    return input_data  # passthrough")
            self._w(f'expr_eval.register_function("{display}", _compute_fn_{snake})')
            self._w()

    # ── Channel Endpoints ──

    def _emit_channel_endpoints(self) -> None:
        if not self.spec.channels:
            return

        self._w()
        self._w("# ── Channel Endpoints ──")
        self._w()

        for ch in self.spec.channels:
            if ch.direction == ChannelDirection.INBOUND and ch.delivery == ChannelDelivery.RELIABLE:
                self._emit_webhook_channel(ch)
            elif ch.direction == ChannelDirection.BIDIRECTIONAL and ch.delivery == ChannelDelivery.REALTIME:
                self._emit_websocket_channel(ch)
            elif ch.direction == ChannelDirection.OUTBOUND and ch.delivery == ChannelDelivery.REALTIME:
                self._emit_sse_channel(ch)
            # Internal channels are handled by existing event mechanisms

    def _emit_webhook_channel(self, ch: ChannelSpec) -> None:
        snake = ch.name.snake
        endpoint = ch.endpoint or f"/webhooks/{snake}"
        table = ch.carries_table

        # Find send scope
        scope = None
        for req in ch.requirements:
            if req.direction == "send":
                scope = req.scope
                break

        scope_dep = f', user=Depends(require_scope("{scope}"))' if scope else ""
        self._w(f'@app.post("{endpoint}")')
        self._w(f"async def webhook_{snake}(request: Request{scope_dep}):")
        self._w(f"    body = await request.json()")
        self._w(f"    db = await get_db()")
        self._w(f"    try:")
        table_obj = self._table_by_snake.get(table)
        if table_obj:
            cols = [c.name for c in table_obj.columns if not c.is_auto]
            placeholders = ", ".join("?" for _ in cols)
            col_names = ", ".join(cols)
            vals = ", ".join(f'body.get("{c}", "")' for c in cols)
            self._w(f'        await db.execute(')
            self._w(f'            "INSERT INTO {table} ({col_names}) VALUES ({placeholders})",')
            self._w(f'            ({vals},)')
            self._w(f'        )')
            self._w(f'        await db.commit()')
        self._w(f'        await event_bus.publish({{"type": "webhook_{snake}", "data": body}})')
        self._w(f'        return {{"status": "accepted"}}')
        self._w(f"    except Exception as e:")
        self._w(f"        terminator.route(TerminError(")
        self._w(f'            source="channel:{snake}",')
        self._w(f'            kind="external",')
        self._w(f"            message=str(e),")
        self._w(f"        ))")
        self._w(f"        raise")
        self._w(f"    finally:")
        self._w(f"        await db.close()")
        self._w()

    def _emit_websocket_channel(self, ch: ChannelSpec) -> None:
        snake = ch.name.snake
        endpoint = ch.endpoint or f"/ws/{snake}"
        self._w(f'@app.websocket("{endpoint}")')
        self._w(f"async def ws_{snake}(websocket: WebSocket):")
        self._w(f"    await websocket.accept()")
        self._w(f"    q = event_bus.subscribe()")
        self._w(f"    try:")
        self._w(f"        while True:")
        self._w(f"            event = await q.get()")
        self._w(f"            await websocket.send_json(event)")
        self._w(f"    except Exception:")
        self._w(f"        event_bus.unsubscribe(q)")
        self._w()

    def _emit_sse_channel(self, ch: ChannelSpec) -> None:
        snake = ch.name.snake
        endpoint = ch.endpoint or f"/channels/{snake}/stream"
        self._w(f'@app.get("{endpoint}")')
        self._w(f"async def channel_sse_{snake}(request: Request):")
        self._w(f"    async def generate():")
        self._w(f"        q = event_bus.subscribe()")
        self._w(f"        try:")
        self._w(f"            while True:")
        self._w(f"                event = await q.get()")
        self._w(f'                yield f"data: {{json.dumps(event)}}\\n\\n"')
        self._w(f"        except asyncio.CancelledError:")
        self._w(f"            event_bus.unsubscribe(q)")
        self._w(f'    return StreamingResponse(generate(), media_type="text/event-stream")')
        self._w()

    # ── Reflection Endpoint ──

    def _emit_reflection_endpoint(self) -> None:
        """Generate a /api/reflect endpoint that serves the AppSpec IR as JSON."""
        # Find the first available read scope for access control
        read_scope = None
        for g in self.spec.access_grants:
            if Verb.VIEW in g.verbs:
                read_scope = g.scope
                break

        # Pre-serialize the IR to a JSON string at compile time
        ir_json_str = self._build_ir_json()

        self._w()
        self._w("# ── Reflection Endpoint ──")
        self._w()

        scope_dep = f', user=Depends(require_scope("{read_scope}"))' if read_scope else ""

        self._w(f'_REFLECT_JSON = {repr(ir_json_str)}')
        self._w()
        self._w(f'@app.get("/api/reflect")')
        self._w(f"async def api_reflect(request: Request{scope_dep}):")
        self._w(f'    """Return the AppSpec IR as JSON for runtime introspection."""')
        self._w(f'    return Response(content=_REFLECT_JSON, media_type="application/json")')
        self._w()

    def _build_ir_json(self) -> str:
        """Serialize the AppSpec to a JSON string at compile time."""
        import dataclasses as dc
        from enum import Enum as _Enum

        def _default(obj):
            if isinstance(obj, _Enum):
                return obj.name
            if isinstance(obj, (frozenset, set)):
                return sorted((o.name if isinstance(o, _Enum) else o) for o in obj)
            raise TypeError(f"Object of type {type(obj).__name__} is not JSON serializable")

        return json.dumps(dc.asdict(self.spec), default=_default)

    # ── SSE Stream ──

    # ── Error Log Endpoint ──

    def _emit_error_log_endpoint(self) -> None:
        self._w()
        self._w("# ── Error Log Endpoint ──")
        self._w()
        self._w('@app.get("/api/errors")')
        self._w("async def api_errors():")
        self._w('    """Return the TerminAtor error log as JSON."""')
        self._w("    return terminator.get_error_log()")
        self._w()

    # ── Events Endpoint ──

    def _emit_events_endpoint(self) -> None:
        self._w()
        self._w("# ── Events Endpoint ──")
        self._w()
        self._w('@app.get("/api/events")')
        self._w("async def api_events(level: str = Query(default=None)):")
        self._w('    """Return recent events with optional level filtering."""')
        self._w("    log = event_bus.get_event_log()")
        self._w("    if level:")
        self._w('        level_order = {"TRACE": 0, "DEBUG": 1, "INFO": 2, "WARN": 3, "ERROR": 4}')
        self._w("        min_level = level_order.get(level.upper(), 0)")
        self._w('        log = [e for e in log if level_order.get(e.get("log_level", "INFO"), 2) >= min_level]')
        self._w("    return log")
        self._w()

    # ── SSE Stream ──

    def _emit_sse_stream(self) -> None:
        for stream in self.spec.streams:
            path = stream.path
            self._w(f'@app.get("{path}")')
            self._w(f"async def sse_stream(request: Request):")
            self._w(f"    async def generate():")
            self._w(f"        q = event_bus.subscribe()")
            self._w(f"        try:")
            self._w(f"            while True:")
            self._w(f"                event = await q.get()")
            self._w(f'                yield f"data: {{json.dumps(event)}}\\n\\n"')
            self._w(f"        except asyncio.CancelledError:")
            self._w(f"            event_bus.unsubscribe(q)")
            self._w(f'    return StreamingResponse(generate(), media_type="text/event-stream")')
            self._w()

    # ── Templates ──

    def _emit_templates(self) -> None:
        self._w("# --- Jinja2 Template Environment ---")
        self._w("jinja_env = Environment(loader=BaseLoader(), autoescape=True)")
        self._w()

        # Base template
        app_name = self.spec.name
        nav_html = self._build_nav_html()

        base_template = f'''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{app_name} - {{{{ page_title }}}}</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://unpkg.com/htmx.org@1.9.10"></script>
    <script src="https://unpkg.com/htmx.org@1.9.10/dist/ext/sse.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body class="bg-gray-50 min-h-screen">
    <nav class="bg-white shadow mb-6">
        <div class="max-w-7xl mx-auto px-4 py-3 flex items-center justify-between">
            <div class="flex items-center space-x-6">
                <span class="text-lg font-bold text-indigo-600">{app_name}</span>
                {nav_html}
            </div>
            <form method="post" action="/set-role" class="flex items-center space-x-2">
                <label class="text-sm text-gray-600">Role:</label>
                <select name="role" onchange="this.form.submit()" class="text-sm border rounded px-2 py-1">
                    {{% for rname in roles %}}
                    <option value="{{{{ rname }}}}" {{% if rname == current_role %}}selected{{% endif %}}>{{{{ rname|title }}}}</option>
                    {{% endfor %}}
                </select>
                {{% if current_role != "anonymous" %}}
                <label class="text-sm text-gray-600 ml-2">Name:</label>
                <input type="text" name="user_name" value="{{{{ current_user_name }}}}"
                       placeholder="Display name" class="text-sm border rounded px-2 py-1 w-28"
                       onchange="this.form.submit()">
                {{% endif %}}
            </form>
        </div>
    </nav>
    <main class="max-w-7xl mx-auto px-4">
        {{{{ content|safe }}}}
    </main>
    <script id="termin-user-data" type="application/json">{{{{ user_profile_json|safe }}}}</script>
    <script type="module">
    // Termin.js Runtime — powered by jexl expression evaluator
    import jexl from "https://cdn.jsdelivr.net/npm/jexl@2.3.0/+esm";
    var profile = JSON.parse(document.getElementById("termin-user-data").textContent);
    var role = "{{{{ current_role }}}}";
    var ctx = {{ role: role, CurrentUser: profile }};
    ctx[role] = {{ CurrentUser: profile }};
    {{{{ termin_compute_js|safe }}}}
    document.querySelectorAll("[data-termin-expr]").forEach(function(el) {{
        jexl.eval(el.dataset.terminExpr, ctx).then(function(result) {{
            el.textContent = result;
        }}).catch(function(err) {{
            el.textContent = "[Error: " + err.message + "]";
        }});
    }});
    </script>
</body>
</html>'''

        self._w(f'BASE_TEMPLATE = jinja_env.from_string({repr(base_template.strip())})')
        self._w()

        # Role switcher endpoint
        self._wblock('''\
            @app.post("/set-role")
            async def set_role(role: str = Form(...), user_name: str = Form("")):
                response = RedirectResponse(url="/", status_code=303)
                response.set_cookie("termin_role", role)
                if user_name:
                    response.set_cookie("termin_user_name", user_name)
                return response
        ''')

        # Generate page templates (merge same-slug pages for role-conditional rendering)
        pages_by_slug: dict[str, list] = {}
        for page in self.spec.pages:
            pages_by_slug.setdefault(page.slug, []).append(page)

        for slug, pages in pages_by_slug.items():
            if len(pages) == 1:
                self._emit_page_template(pages[0])
            else:
                self._emit_merged_page_template(slug, pages)

    def _build_nav_html(self) -> str:
        if not self.spec.nav_items:
            return ""

        role_names = [r.name for r in self.spec.auth.roles]
        items_html = []
        for item in self.spec.nav_items:
            slug = item.page_slug
            href = f"/{slug}"

            # Visibility check
            if "all" in item.visible_to:
                vis = ""
            else:
                role_checks = " or ".join(
                    f'current_role == "{r}"' if r in role_names
                    else f'"{r}" in current_role'
                    for r in item.visible_to
                )
                vis = f'{{% if {role_checks} %}}'

            badge_html = ""
            if item.badge_table:
                badge_html = (
                    f' <span class="ml-1 bg-red-500 text-white text-xs rounded-full px-2 py-0.5">'
                    f'{{{{ badge_{_snake(item.label)} }}}}</span>'
                )

            link = f'<a href="{href}" class="text-gray-700 hover:text-indigo-600">{item.label}{badge_html}</a>'
            if vis:
                link = f"{vis}{link}{{% endif %}}"
            items_html.append(link)

        return "\n                ".join(items_html)

    def _emit_page_template(self, page: PageSpec) -> None:
        slug = page.slug
        template_parts = [f'<h1 class="text-2xl font-bold mb-4">{page.name}</h1>']

        # Static text blocks
        for text in page.static_texts:
            template_parts.append(
                f'<div class="text-lg text-gray-800 mb-4">{text}</div>'
            )

        # Expression blocks (evaluated client-side by termin.js)
        for expr in page.static_expressions:
            template_parts.append(
                f'<div class="text-lg text-gray-800 mb-4" data-termin-expr="{expr}">...</div>'
            )

        # Display table
        if page.display_table and page.table_columns:
            template_parts.append(self._gen_table_html(page))

        # Form
        if page.form_fields:
            template_parts.append(self._gen_form_html(page))

        # Aggregations
        for agg in page.aggregations:
            template_parts.append(self._gen_aggregation_html(agg))

        # Chart
        if page.chart:
            template_parts.append(self._gen_chart_html(page.chart))

        template_content = "\n".join(template_parts)
        var_name = f"TEMPLATE_{slug.upper()}"
        self._w(f'{var_name} = jinja_env.from_string({repr(template_content)})')
        self._w()

    def _gen_table_html(self, page: PageSpec) -> str:
        table = page.display_table
        cols = page.table_columns

        parts = []

        # Filter form
        if page.filters:
            parts.append('<form method="get" class="mb-4 flex gap-4 items-end">')
            for ff in page.filters:
                fname = ff.key
                display = ff.display
                dfl = "{{" + f" filters.{fname}|default('') " + "}}"

                if ff.filter_type == "status":
                    parts.append(f'  <div>')
                    parts.append(f'    <label class="block text-sm text-gray-600">{display}</label>')
                    parts.append(f'    <select name="{fname}" class="border rounded px-2 py-1 text-sm">')
                    parts.append(f'      <option value="">All</option>')
                    for state in ff.options:
                        sel = "{{" + f' "selected" if filters.{fname}|default("") == "{state}" else "" ' + "}}"
                        parts.append(f'      <option value="{state}" {sel}>{state}</option>')
                    parts.append(f'    </select>')
                    parts.append(f'  </div>')
                elif ff.filter_type == "enum":
                    parts.append(f'  <div>')
                    parts.append(f'    <label class="block text-sm text-gray-600">{display}</label>')
                    parts.append(f'    <select name="{fname}" class="border rounded px-2 py-1 text-sm">')
                    parts.append(f'      <option value="">All</option>')
                    for val in ff.options:
                        sel = "{{" + f' "selected" if filters.{fname}|default("") == "{val}" else "" ' + "}}"
                        parts.append(f'      <option value="{val}" {sel}>{val}</option>')
                    parts.append(f'    </select>')
                    parts.append(f'  </div>')
                elif ff.filter_type == "distinct":
                    parts.append(f'  <div>')
                    parts.append(f'    <label class="block text-sm text-gray-600">{display}</label>')
                    parts.append(f'    <select name="{fname}" class="border rounded px-2 py-1 text-sm">')
                    parts.append(f'      <option value="">All</option>')
                    parts.append(f'      {{% for wh in warehouse_options %}}')
                    sel = "{{" + f' "selected" if filters.{fname}|default("") == wh else "" ' + "}}"
                    parts.append(f'      <option value="{{{{ wh }}}}" {sel}>{{{{ wh }}}}</option>')
                    parts.append(f'      {{% endfor %}}')
                    parts.append(f'    </select>')
                    parts.append(f'  </div>')
                else:
                    parts.append(f'  <div>')
                    parts.append(f'    <label class="block text-sm text-gray-600">{display}</label>')
                    parts.append(f'    <input type="text" name="{fname}" value="{dfl}" class="border rounded px-2 py-1 text-sm">')
                    parts.append(f'  </div>')
            parts.append('  <button type="submit" class="bg-indigo-600 text-white px-4 py-1 rounded text-sm">Filter</button>')
            parts.append('</form>')

        # Search form
        if page.search_fields:
            parts.append('<form method="get" class="mb-4">')
            fields_str = " or ".join(page.search_fields)
            q_dfl = "{{ q|default('') }}"
            parts.append(f'  <input type="text" name="q" value="{q_dfl}" placeholder="Search by {fields_str}..." class="border rounded px-3 py-2 w-64 text-sm">')
            parts.append('  <button type="submit" class="bg-gray-200 px-3 py-2 rounded text-sm ml-2">Search</button>')
            parts.append('</form>')

        # SSE wrapper
        sse_attrs = ""
        if page.subscribe_stream:
            stream_path = self.spec.streams[0].path if self.spec.streams else "/api/v1/stream"
            sse_attrs = f' hx-ext="sse" sse-connect="{stream_path}" sse-swap="message" hx-swap="innerHTML"'

        parts.append(f'<div id="{table}-table"{sse_attrs}>')
        parts.append('<table class="w-full bg-white shadow rounded overflow-hidden">')
        parts.append('  <thead class="bg-gray-100">')
        parts.append('    <tr>')
        for tc in cols:
            parts.append(f'      <th class="px-4 py-2 text-left text-sm font-medium text-gray-600">{tc.display}</th>')
        if page.related:
            # Use the related table name for the header (convert snake to display)
            related_display = page.related.related_table.replace("_", " ")
            parts.append(f'      <th class="px-4 py-2 text-left text-sm font-medium text-gray-600">{related_display}</th>')
        parts.append('    </tr>')
        parts.append('  </thead>')
        parts.append('  <tbody>')
        parts.append(f'    {{% for item in items %}}')

        # Row highlight
        if page.highlight:
            f1 = page.highlight.field
            f2 = page.highlight.threshold_field
            parts.append(f'    <tr class="{{% set v1 = item["{f1}"]|default(none) %}}{{% set v2 = item["{f2}"]|default(none) %}}{{% if v1 is not none and v2 is not none and v1 <= v2 %}}bg-red-50{{% else %}}bg-white{{% endif %}} border-t">')
        else:
            parts.append('    <tr class="border-t">')

        for tc in cols:
            col_key = tc.key
            col_dfl = "{{" + f" item.{col_key}|default('') " + "}}"
            parts.append(f'      <td class="px-4 py-2 text-sm">{col_dfl}</td>')

        if page.related:
            rel_dfl = "{{ item.related|default('') }}"
            parts.append(f'      <td class="px-4 py-2 text-sm">{rel_dfl}</td>')

        parts.append('    </tr>')
        parts.append('    {% endfor %}')
        parts.append('  </tbody>')
        parts.append('</table>')
        parts.append('</div>')

        return "\n".join(parts)

    def _gen_form_html(self, page: PageSpec) -> str:
        form_table = page.form_target_table
        if not form_table:
            return '<p>Form configuration error</p>'

        slug = page.slug

        parts = []
        parts.append(f'<form method="post" action="/{slug}" class="bg-white shadow rounded p-6 max-w-lg">')

        for ff in page.form_fields:
            col = ff.key
            display = ff.display

            if ff.input_type == "enum":
                parts.append(f'  <div class="mb-4">')
                parts.append(f'    <label class="block text-sm font-medium text-gray-700 mb-1">{display}</label>')
                parts.append(f'    <select name="{col}" class="w-full border rounded px-3 py-2">')
                parts.append(f'      <option value="">Select...</option>')
                for val in ff.enum_values:
                    parts.append(f'      <option value="{val}">{val}</option>')
                parts.append(f'    </select>')
                parts.append(f'  </div>')
                continue

            if ff.input_type == "reference":
                ref_table = ff.reference_table
                ref_display = ff.reference_display_col or "id"
                ref_unique = ff.reference_unique_col

                extra_attrs = ""
                if ff.required:
                    extra_attrs += " required"

                if ref_unique and ref_unique != ref_display:
                    option_label = f'{{{{ item.{ref_display} }}}} ({{{{ item.{ref_unique} }}}})'
                else:
                    option_label = f'{{{{ item.{ref_display} }}}}'

                # Find the display name of the referenced content
                ref_display_name = ref_table.replace("_", " ")
                # Try to find the actual content display name from tables
                ref_table_obj = self._table_by_snake.get(ref_table)
                if ref_table_obj:
                    ref_display_name = ref_table_obj.name.display

                parts.append(f'  <div class="mb-4">')
                parts.append(f'    <label class="block text-sm font-medium text-gray-700 mb-1">{display}</label>')
                parts.append(f'    <select name="{col}" class="w-full border rounded px-3 py-2"{extra_attrs}>')
                parts.append(f'      <option value="">Select {ref_display_name}...</option>')
                parts.append(f'      {{% for item in {ref_table}_list %}}')
                parts.append(f'      <option value="{{{{ item.id }}}}">{option_label}</option>')
                parts.append(f'      {{% endfor %}}')
                parts.append(f'    </select>')
                parts.append(f'  </div>')
                continue

            # Standard input types
            input_type = "text"
            extra_attrs = ""
            if ff.input_type == "currency":
                input_type = "number"
                extra_attrs = ' step="0.01"'
            elif ff.input_type == "number":
                input_type = "number"
                if ff.minimum is not None:
                    extra_attrs = f' min="{ff.minimum}"'

            if ff.required:
                extra_attrs += " required"

            parts.append(f'  <div class="mb-4">')
            parts.append(f'    <label class="block text-sm font-medium text-gray-700 mb-1">{display}</label>')
            parts.append(f'    <input type="{input_type}" name="{col}" class="w-full border rounded px-3 py-2"{extra_attrs}>')
            parts.append(f'  </div>')

        parts.append(f'  <input type="hidden" name="edit_id" value="">')
        parts.append(f'  <button type="submit" class="bg-indigo-600 text-white px-6 py-2 rounded hover:bg-indigo-700">Save</button>')
        parts.append(f'</form>')

        # Auto-generate CRUD table if page has no explicit display table
        if not page.display_table:
            table_obj = self._table_by_snake.get(form_table)
            if table_obj:
                display_cols = ["id"] + [ff.key for ff in page.form_fields]
                if table_obj.has_status_column and "status" not in display_cols:
                    display_cols.append("status")

                # Add automatic timestamp columns
                for col_def in table_obj.columns:
                    if col_def.is_auto and col_def.name not in display_cols:
                        display_cols.append(col_def.name)

                parts.append(f'<h2 class="text-xl font-semibold mt-8 mb-4">Existing {table_obj.name.display.title()}</h2>')
                parts.append(f'<div class="w-full bg-white shadow rounded overflow-hidden">')
                parts.append(f'<table class="w-full">')
                parts.append(f'  <thead class="bg-gray-100">')
                parts.append(f'    <tr>')
                for col_name in display_cols:
                    parts.append(f'      <th class="px-4 py-2 text-left text-sm font-medium text-gray-600">{col_name.replace("_", " ")}</th>')
                parts.append(f'      <th class="px-4 py-2 text-left text-sm font-medium text-gray-600">actions</th>')
                parts.append(f'    </tr>')
                parts.append(f'  </thead>')
                parts.append(f'  <tbody>')
                parts.append(f'    {{% for row in {form_table}_rows %}}')
                parts.append(f'    <tr class="border-t">')
                for col_name in display_cols:
                    parts.append(f'      <td class="px-4 py-2 text-sm">{{{{ row.{col_name}|default("") }}}}</td>')
                # Edit button JS
                js_fill_parts = []
                for ff in page.form_fields:
                    col_name = ff.key
                    js_fill_parts.append(f"""el=document.querySelector('[name="{col_name}"]');if(el){{if(el.tagName==="SELECT"){{for(var i=0;i<el.options.length;i++)if(el.options[i].value==row.{col_name})el.selectedIndex=i;}}else el.value=row.{col_name};}}""")
                js_fill = "".join(js_fill_parts)
                js_edit = f"var row={{{{row|tojson}}}};document.querySelector('[name=\\'edit_id\\']').value=row.id;{js_fill}window.scrollTo(0,0);return false;"
                parts.append(f'      <td class="px-4 py-2 text-sm">')
                parts.append(f'        <a href="#" onclick=\'{js_edit}\' class="text-indigo-600 hover:underline mr-3">Edit</a>')
                parts.append(f'        <form method="post" action="/{slug}/delete/{{{{ row.id }}}}" class="inline" onsubmit="return confirm(\'Delete this record?\')">')
                parts.append(f'          <button type="submit" class="text-red-600 hover:underline">Delete</button>')
                parts.append(f'        </form>')
                parts.append(f'      </td>')
                parts.append(f'    </tr>')
                parts.append(f'    {{% endfor %}}')
                parts.append(f'  </tbody>')
                parts.append(f'</table>')
                parts.append(f'</div>')

        return "\n".join(parts)

    def _gen_aggregation_html(self, agg: AggregationSpec) -> str:
        slug = agg.key
        return (
            f'<div class="bg-white shadow rounded p-4 mb-4">'
            f'  <div class="text-sm text-gray-600">{agg.description}</div>'
            f'  <div class="text-2xl font-bold mt-1">{{{{ {slug} }}}}</div>'
            f'</div>'
        )

    def _gen_chart_html(self, chart: ChartSpec) -> str:
        chart_id = chart.table + "_chart"
        return (
            f'<div class="bg-white shadow rounded p-4 mb-4">'
            f'  <canvas id="{chart_id}" height="200"></canvas>'
            f'</div>'
            f'<script>'
            f'fetch("/api/chart-data/{chart.table}")'
            f'.then(r=>r.json()).then(data=>{{'
            f'new Chart(document.getElementById("{chart_id}"),{{'
            f'type:"line",data:{{labels:data.labels,datasets:[{{label:"{chart.table}",data:data.values,borderColor:"rgb(79,70,229)",tension:0.1}}]}}'
            f'}});}});'
            f'</script>'
        )

    def _emit_merged_page_template(self, slug: str, pages: list) -> None:
        """Emit a single template for multiple pages sharing the same slug but different roles."""
        template_parts = [f'<h1 class="text-2xl font-bold mb-4">{pages[0].name}</h1>']

        for page in pages:
            role = page.role
            role_cond = f'{{% if current_role == "{role}" or current_role|lower == "{role.lower()}" %}}'
            parts = []

            for text in page.static_texts:
                parts.append(f'<div class="text-lg text-gray-800 mb-4">{text}</div>')
            for expr in page.static_expressions:
                parts.append(f'<div class="text-lg text-gray-800 mb-4" data-termin-expr="{expr}">...</div>')
            if page.display_table and page.table_columns:
                parts.append(self._gen_table_html(page))
            if page.form_fields:
                parts.append(self._gen_form_html(page))

            if parts:
                template_parts.append(role_cond)
                template_parts.extend(parts)
                template_parts.append('{% endif %}')

        template_content = "\n".join(template_parts)
        var_name = f"TEMPLATE_{slug.upper()}"
        self._w(f'{var_name} = jinja_env.from_string({repr(template_content)})')
        self._w()

    # ── Compute-to-JS Compilation ──

    def _compile_compute_to_js(self, comp: 'ComputeSpec') -> str:
        """Compile a compute body to a JavaScript function body."""
        # Body lines may be raw or bracket-stripped JEXL: "greeting = expr"
        for line in comp.body_lines:
            # Strip any remaining brackets (belt and suspenders)
            clean = line.strip()
            if clean.startswith('[') and clean.endswith(']'):
                clean = clean[1:-1].strip()
            m = re.match(r'(\w+)\s*=\s*(.*)', clean)
            if m:
                expr = m.group(2).strip()
                return f'return {expr};'
        return 'return "TODO: implement";'

    # ── Page Routes ──

    def _emit_page_routes(self) -> None:
        # Home route -> redirect to first page
        if self.spec.pages:
            first_slug = self.spec.pages[0].slug
            self._w(f'@app.get("/", response_class=HTMLResponse)')
            self._w(f"async def home(request: Request):")
            self._w(f'    return RedirectResponse(url="/{first_slug}")')
            self._w()

        # Emit one route per unique slug (merged pages share a route)
        emitted_slugs: set[str] = set()
        for page in self.spec.pages:
            if page.slug not in emitted_slugs:
                self._emit_page_route(page)
                emitted_slugs.add(page.slug)

    def _emit_page_route(self, page: PageSpec) -> None:
        slug = page.slug
        var_name = f"TEMPLATE_{slug.upper()}"

        # GET route
        self._w(f'@app.get("/{slug}", response_class=HTMLResponse)')
        self._w(f"async def page_{slug}(request: Request):")
        self._w(f'    user = get_current_user(request)')
        self._w(f'    q = request.query_params.get("q", "")')
        self._w(f'    db = await get_db()')
        self._w(f'    try:')
        self._w(f'        context = {{')
        self._w(f'            "page_title": "{page.name}",')
        self._w(f'            "current_role": user["role"],')
        self._w(f'            "current_user_name": user["profile"]["DisplayName"],')
        self._w(f'            "user_profile_json": json.dumps(user["profile"]),')
        self._w(f'            "roles": list(ROLES.keys()),')
        self._w(f'            "q": q,')
        self._w(f'        }}')

        if page.display_table:
            table = page.display_table
            self._w(f'        query = "SELECT * FROM {table}"')
            self._w(f'        params = []')
            self._w(f'        conditions = []')

            # Filter support — only apply filters for columns on the display table
            table_obj = next((t for t in self.spec.tables if t.name.snake == table), None)
            table_cols = {c.name for c in table_obj.columns} if table_obj else set()
            if table_obj and table_obj.has_status_column:
                table_cols.add("status")
            if page.filters:
                for ff in page.filters:
                    fname = ff.key
                    self._w(f'        {fname}_val = request.query_params.get("{fname}", "")')
                    if fname in table_cols:
                        self._w(f'        if {fname}_val:')
                        self._w(f'            conditions.append("{fname} = ?")')
                        self._w(f'            params.append({fname}_val)')

            # Search support
            if page.search_fields:
                search_cols = list(page.search_fields)
                or_clauses = " OR ".join(f"{c} LIKE ?" for c in search_cols)
                self._w(f'        if q:')
                self._w(f'            conditions.append("({or_clauses})")')
                for _ in search_cols:
                    self._w(f'            params.append(f"%{{q}}%")')

            self._w(f'        if conditions:')
            self._w(f'            query += " WHERE " + " AND ".join(conditions)')
            self._w(f'        cursor = await db.execute(query, params)')
            self._w(f'        rows = await cursor.fetchall()')
            self._w(f'        context["items"] = [dict(r) for r in rows]')
            self._w(f'        context["filters"] = dict(request.query_params)')

            # Populate distinct options for "distinct" type filters
            for ff in page.filters:
                if ff.filter_type == "distinct":
                    # Find which table has this column (may be a related table, not the display table)
                    distinct_table = table
                    for t in self.spec.tables:
                        if any(c.name == ff.key for c in t.columns) and t.name.snake != table:
                            distinct_table = t.name.snake
                            break
                    self._w(f'        wh_cursor = await db.execute("SELECT DISTINCT {ff.key} FROM {distinct_table} ORDER BY {ff.key}")')
                    self._w(f'        context["warehouse_options"] = [r["{ff.key}"] for r in await wh_cursor.fetchall()]')

            # Show related
            if page.related:
                related_table = page.related.related_table
                join_column = page.related.join_column
                display_cols = page.related.display_columns
                group_col = display_cols[0] if display_cols else "product"
                self._w(f'        for item in context["items"]:')
                self._w(f'            rcursor = await db.execute("SELECT * FROM {related_table} WHERE product = ?", (item["id"],))')
                self._w(f'            related_rows = [dict(r) for r in await rcursor.fetchall()]')
                self._w(f'            item["related"] = ", ".join(str(r.get("{group_col}", "")) + ":" + str(r.get("quantity", "")) for r in related_rows)')

        # Aggregations
        for agg in page.aggregations:
            slug_agg = agg.key
            if agg.agg_type == "count_by_status":
                tbl = agg.table
                self._w(f'        cursor_agg = await db.execute("SELECT COUNT(*) as total, status FROM {tbl} GROUP BY status")')
                self._w(f'        agg_rows = await cursor_agg.fetchall()')
                self._w("        agg_rows = [dict(r) for r in agg_rows]")
                self._w("        breakdown_parts = [str(r['status']) + ': ' + str(r['total']) for r in agg_rows]")
                self._w("        breakdown = ', '.join(breakdown_parts)")
                self._w("        total = sum(r['total'] for r in agg_rows)")
                self._w('        context["' + slug_agg + '"] = str(total) + " (" + breakdown + ")"')
            elif agg.agg_type == "count":
                tbl = agg.table
                self._w(f'        cursor_agg = await db.execute("SELECT COUNT(*) as cnt FROM {tbl}")')
                self._w(f'        context["{slug_agg}"] = (await cursor_agg.fetchone())["cnt"]')
            elif agg.agg_type == "sum_join":
                self._w(f'        cursor_agg = await db.execute("SELECT COALESCE(SUM(sl.quantity * p.unit_cost), 0) as val FROM stock_levels sl JOIN products p ON sl.product = p.id")')
                self._w("        val = (await cursor_agg.fetchone())['val']")
                self._w('        context["' + slug_agg + '"] = f"${val:.2f}"')

        # Nav badges
        for nav_item in self.spec.nav_items:
            if nav_item.badge_table:
                badge_slug = _snake(nav_item.label)
                badge_table = nav_item.badge_table
                self._w(f'        cursor_badge = await db.execute("SELECT COUNT(*) as cnt FROM {badge_table}")')
                self._w(f'        context["badge_{badge_slug}"] = (await cursor_badge.fetchone())["cnt"]')

        # Chart: data fetched via separate API
        if page.chart:
            self._w(f'        # Chart data is fetched via separate API endpoint')

        # Fetch reference lists for form dropdowns + existing records for CRUD table
        if page.form_fields:
            form_table = page.form_target_table
            if form_table:
                for ff in page.form_fields:
                    if ff.input_type == "reference" and ff.reference_table:
                        ref_table = ff.reference_table
                        self._w(f'        ref_cursor = await db.execute("SELECT * FROM {ref_table}")')
                        self._w(f'        context["{ref_table}_list"] = [dict(r) for r in await ref_cursor.fetchall()]')

                # Fetch existing records for the auto-generated CRUD table
                if not page.display_table:
                    self._w(f'        rows_cursor = await db.execute("SELECT * FROM {form_table} ORDER BY id DESC")')
                    self._w(f'        context["{form_table}_rows"] = [dict(r) for r in await rows_cursor.fetchall()]')

        # Generate jexl function registrations for termin.js runtime
        compute_js_parts = []
        for comp in self.spec.computes:
            if comp.body_lines and comp.input_params:
                param_name = comp.input_params[0].name if comp.input_params else "x"
                body_js = self._compile_compute_to_js(comp)
                compute_js_parts.append(
                    f'jexl.addFunction("{comp.name.display}", function({param_name}) {{ {body_js} }});'
                )
        self._w(f'        context["termin_compute_js"] = {repr(chr(10).join(compute_js_parts))}')

        self._w(f'        content_html = {var_name}.render(**context)')
        self._w(f'        return BASE_TEMPLATE.render(content=content_html, **context)')
        self._w(f'    finally:')
        self._w(f'        await db.close()')
        self._w()

        # POST route for form pages
        if page.form_fields and page.form_target_table:
            self._emit_form_post_route(page)

    def _emit_form_post_route(self, page: PageSpec) -> None:
        slug = page.slug
        form_table = page.form_target_table
        table_obj = self._table_by_snake.get(form_table)

        scope = page.required_scope
        scope_dep = f', user=Depends(require_scope("{scope}"))' if scope else ""

        # Determine initial state (only if table has a state machine)
        initial_state = page.create_as_status
        validate_field = page.validate_unique_field

        form_params = []
        for ff in page.form_fields:
            form_params.append(f'{ff.key}: str = Form("")')

        params_str = ", ".join(form_params)

        self._w(f'@app.post("/{slug}", response_class=HTMLResponse)')
        self._w(f"async def page_{slug}_post(request: Request, edit_id: str = Form(\"\"), {params_str}{scope_dep}):")
        self._w(f'    db = await get_db()')
        self._w(f'    try:')

        # Cast form string values to proper types
        for ff in page.form_fields:
            col = ff.key
            if ff.input_type == "number" or ff.input_type == "reference":
                self._w(f'        {col} = int({col}) if {col} else None')
            elif ff.input_type == "currency":
                self._w(f'        {col} = float({col}) if {col} else None')

        self._w(f'        if edit_id:')
        # UPDATE path
        update_cols = [ff.key for ff in page.form_fields]
        set_clause = ", ".join(f'{c} = ?' for c in update_cols)
        values_str_update = ", ".join(update_cols)
        self._w(f'            await db.execute(')
        self._w(f'                "UPDATE {form_table} SET {set_clause} WHERE id = ?",')
        self._w(f'                ({values_str_update}, int(edit_id),)')
        self._w(f'            )')
        self._w(f'        else:')

        # INSERT path
        insert_cols = [ff.key for ff in page.form_fields]
        if initial_state:
            insert_cols.append("status")
        cols_sql = ", ".join(insert_cols)
        placeholders = ", ".join(["?"] * len(insert_cols))
        values_list = [ff.key for ff in page.form_fields]
        if initial_state:
            values_list.append(f'"{initial_state}"')
        values_str = ", ".join(values_list)

        # Uniqueness validation (only on insert)
        if validate_field:
            vcol = validate_field
            self._w(f'            cursor = await db.execute("SELECT id FROM {form_table} WHERE {vcol} = ?", ({vcol},))')
            self._w(f'            if await cursor.fetchone():')
            # Find the display name for the field
            display_name = validate_field
            for ff in page.form_fields:
                if ff.key == validate_field:
                    display_name = ff.display
                    break
            self._w(f'                raise HTTPException(status_code=422, detail="{display_name} already exists")')

        self._w(f'            await db.execute(')
        self._w(f'                "INSERT INTO {form_table} ({cols_sql}) VALUES ({placeholders})",')
        self._w(f'                ({values_str},)')
        self._w(f'            )')
        self._w(f'        await db.commit()')
        self._w(f'        return RedirectResponse(url="/{slug}", status_code=303)')
        self._w(f'    finally:')
        self._w(f'        await db.close()')
        self._w()

        # DELETE route for CRUD table (only when page has no explicit display table)
        if not page.display_table:
            del_scope = (
                self._scope_for_verb(form_table, Verb.DELETE) or
                self._scope_for_verb(form_table, Verb.UPDATE) or
                page.required_scope
            )
            del_scope_dep = f', user=Depends(require_scope("{del_scope}"))' if del_scope else ""
            self._w(f'@app.post("/{slug}/delete/{{record_id}}", response_class=HTMLResponse)')
            self._w(f"async def page_{slug}_delete(record_id: int{del_scope_dep}):")
            self._w(f'    db = await get_db()')
            self._w(f'    try:')
            self._w(f'        await db.execute("DELETE FROM {form_table} WHERE id = ?", (record_id,))')
            self._w(f'        await db.commit()')
            self._w(f'        return RedirectResponse(url="/{slug}", status_code=303)')
            self._w(f'    finally:')
            self._w(f'        await db.close()')
            self._w()

    # ── Chart data API ──

    def _emit_chart_data_routes(self) -> None:
        for page in self.spec.pages:
            if page.chart:
                table = page.chart.table
                days = page.chart.days
                self._w(f'@app.get("/api/chart-data/{table}")')
                self._w(f"async def chart_data_{table}():")
                self._w(f'    db = await get_db()')
                self._w(f'    try:')
                sql = (f"SELECT DATE(created_at) as day, COUNT(*) as cnt "
                       f"FROM {table} "
                       f"WHERE created_at >= DATE('now', '-{days} days') "
                       f"GROUP BY DATE(created_at) ORDER BY day")
                self._w(f'        cursor = await db.execute("{sql}")')
                self._w(f'        rows = await cursor.fetchall()')
                self._w(f'        return {{"labels": [dict(r)["day"] for r in rows], "values": [dict(r)["cnt"] for r in rows]}}')
                self._w(f'    finally:')
                self._w(f'        await db.close()')
                self._w()

    # ── Startup ──

    def _emit_startup(self) -> None:
        self._emit_chart_data_routes()
        self._emit_lifespan()

    # ── Lifespan ──

    def _emit_lifespan(self) -> None:
        self._w()
        self._w("# ── Runtime Startup Lifecycle ──")
        self._w()
        self._w("@asynccontextmanager")
        self._w("async def lifespan(app):")

        # Phase 0: Bootstrap
        self._w('    # Phase 0: Bootstrap')
        self._w('    print("[Termin] Phase 0: Bootstrap")')
        self._w()

        # Phase 1: Error Infrastructure
        self._w('    # Phase 1: Error Infrastructure')
        self._w('    print("[Termin] Phase 1: TerminAtor initialized")')
        self._w()

        # Phase 2: Expression Evaluator
        self._w('    # Phase 2: Expression Evaluator')
        self._w('    print("[Termin] Phase 2: Expression evaluator ready")')

        # Register compute functions
        for comp in self.spec.computes:
            snake = comp.name.snake
            display = comp.name.display
            self._w(f'    # Registered compute: {display}')
        self._w()

        # Phase 3: Data Layer
        self._w('    # Phase 3: Data Layer')
        self._w('    print("[Termin] Phase 3: Initializing storage")')
        self._w('    await init_db()')
        self._w()

        # Phase 4: Primitives
        self._w('    # Phase 4: Primitives')
        self._w('    print("[Termin] Phase 4: Registering primitives")')

        # Register state machines
        for sm in self.spec.state_machines:
            self._w(f'    # State machine: {sm.machine_name} for {sm.table}')

        # Register channels
        for ch in self.spec.channels:
            self._w(f'    # Channel: {ch.name.display}')

        # Register boundaries
        for bnd in self.spec.boundaries:
            self._w(f'    # Boundary: {bnd.name.display}')

        # Register events
        for ev in self.spec.events:
            self._w(f'    # Event: {ev.source_table} {ev.trigger}')
        self._w()

        # Phase 5: Serve
        self._w('    # Phase 5: Serve')
        self._w('    print("[Termin] Phase 5: Ready to serve")')
        self._w('    yield')
        self._w()

        # Shutdown
        self._w('    # Shutdown')
        self._w('    print("[Termin] Shutting down...")')
        self._w()

        self._w("app.router.lifespan_context = lifespan")
        self._w()

    # ── Main ──

    def _emit_main(self) -> None:
        app_name = self.spec.name
        self._wblock(f'''\
            if __name__ == "__main__":
                import argparse
                parser = argparse.ArgumentParser(description="{app_name}")
                parser.add_argument("--port", "-p", type=int, default=8000, help="Port to listen on (default: 8000)")
                parser.add_argument("--host", default="0.0.0.0", help="Host to bind to (default: 0.0.0.0)")
                args = parser.parse_args()
                uvicorn.run(app, host=args.host, port=args.port)
        ''')
