# Copyright 2026 Jamie-Leigh Blake
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0

"""Runtime backend: AppSpec (IR) -> slim Python file that uses termin_runtime.

The generated app.py is ~17 lines: it embeds the IR JSON and calls
create_termin_app() from the termin_runtime package.

Use with: termin compile app.termin -o app.py --backend runtime
"""

import json
from dataclasses import asdict
from datetime import datetime, timezone
from enum import Enum


def _ir_json_default(obj):
    if isinstance(obj, Enum):
        return obj.name
    if isinstance(obj, (frozenset, set)):
        return sorted((o.name if isinstance(o, Enum) else o) for o in obj)
    raise TypeError(f"{type(obj).__name__} not serializable")


def _simplify_props(obj):
    """Simplify PropValue dicts: {value: x, is_expr: false} → bare x."""
    if isinstance(obj, dict):
        for k, v in list(obj.items()):
            if isinstance(v, dict) and set(v.keys()) == {"value", "is_expr"}:
                if not v["is_expr"]:
                    obj[k] = v["value"]
            elif isinstance(v, (dict, list)):
                _simplify_props(v)
    elif isinstance(obj, list):
        for i, item in enumerate(obj):
            if isinstance(item, dict) and set(item.keys()) == {"value", "is_expr"}:
                if not item["is_expr"]:
                    obj[i] = item["value"]
            elif isinstance(item, (dict, list)):
                _simplify_props(item)


class RuntimeBackend:
    """Slim backend that generates a termin_runtime-based app."""

    name = "runtime"

    def generate(self, spec, source_file: str = "") -> str:
        now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        ir_dict = asdict(spec)
        _simplify_props(ir_dict)
        ir_json = json.dumps(ir_dict, indent=2, default=_ir_json_default)
        # Store IR and app code separately — the generate() return is the .py,
        # but we stash the IR JSON for the CLI to write as a companion file
        self._ir_json = ir_json

        return f'''"""Generated by Termin Compiler from {source_file}
Compiled at: {now}
Backend: runtime (uses termin_runtime package)

Reads the IR from a companion .json file (same name as this file).
The IR is the compiled Intermediate Representation of your .termin
file. It is deterministic output — recompile to regenerate.
"""
import argparse
import json
from pathlib import Path
from termin_runtime import create_termin_app

_ir_path = Path(__file__).with_suffix(".json")
IR_JSON = _ir_path.read_text(encoding="utf-8")

# Load seed data if a companion _seed.json exists
_seed_path = Path(__file__).with_name(Path(__file__).stem + "_seed.json")
_seed_data = None
if _seed_path.exists():
    _seed_data = json.loads(_seed_path.read_text(encoding="utf-8"))

# Deploy config: <app_name>.deploy.json provides channel URLs, auth, etc.
_app_stem = Path(__file__).stem.replace("_app", "")
_deploy_path = Path(__file__).with_name(f"{{_app_stem}}.deploy.json")
_deploy_config = None
if _deploy_path.exists():
    _deploy_config = json.loads(_deploy_path.read_text(encoding="utf-8"))

app = create_termin_app(IR_JSON, seed_data=_seed_data,
                        deploy_config=_deploy_config,
                        strict_channels=(_deploy_config is not None))

if __name__ == "__main__":
    import uvicorn
    parser = argparse.ArgumentParser()
    parser.add_argument("-p", "--port", type=int, default=8000)
    parser.add_argument("--seed", type=str, default=None,
                        help="Path to a JSON seed file (dict of content_name -> [records])")
    parser.add_argument("--deploy", type=str, default=None,
                        help="Path to deploy config JSON file")
    args = parser.parse_args()
    if args.seed:
        seed_path = Path(args.seed)
        if seed_path.exists():
            _seed_data = json.loads(seed_path.read_text(encoding="utf-8"))
    if args.deploy:
        _deploy_config = json.loads(Path(args.deploy).read_text(encoding="utf-8"))
    app = create_termin_app(IR_JSON, seed_data=_seed_data,
                            deploy_config=_deploy_config,
                            strict_channels=(_deploy_config is not None))
    uvicorn.run(app, host="0.0.0.0", port=args.port)
'''

    def required_dependencies(self) -> list[str]:
        return [
            "termin-runtime",
            "fastapi>=0.100.0",
            "uvicorn>=0.23.0",
            "websockets>=12.0",
            "aiosqlite>=0.19.0",
            "jinja2>=3.1.0",
            "python-multipart>=0.0.6",
            "cel-python>=0.5.0",
        ]
