"""Runtime backend: AppSpec (IR) -> slim Python file that uses termin_runtime.

The generated app.py is ~17 lines: it embeds the IR JSON and calls
create_termin_app() from the termin_runtime package.

Use with: termin compile app.termin -o app.py --backend runtime
"""

import json
from dataclasses import asdict
from datetime import datetime, timezone
from enum import Enum


def _ir_json_default(obj):
    if isinstance(obj, Enum):
        return obj.name
    if isinstance(obj, (frozenset, set)):
        return sorted((o.name if isinstance(o, Enum) else o) for o in obj)
    raise TypeError(f"{type(obj).__name__} not serializable")


class RuntimeBackend:
    """Slim backend that generates a termin_runtime-based app."""

    name = "runtime"

    def generate(self, spec, source_file: str = "") -> str:
        now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        ir_json = json.dumps(asdict(spec), indent=None, default=_ir_json_default)

        return f'''"""Generated by Termin Compiler from {source_file}
Compiled at: {now}
Backend: runtime (uses termin_runtime package)
"""
import argparse
from termin_runtime import create_termin_app

IR_JSON = {repr(ir_json)}

app = create_termin_app(IR_JSON)

if __name__ == "__main__":
    import uvicorn
    parser = argparse.ArgumentParser()
    parser.add_argument("-p", "--port", type=int, default=8000)
    args = parser.parse_args()
    uvicorn.run(app, host="0.0.0.0", port=args.port)
'''

    def required_dependencies(self) -> list[str]:
        return [
            "termin-runtime",
            "fastapi>=0.100.0",
            "uvicorn>=0.23.0",
            "aiosqlite>=0.19.0",
            "jinja2>=3.1.0",
            "python-multipart>=0.0.6",
            "pyjexl>=0.3.0",
        ]
