"""Code generator: AST -> single Python file (app.py).

Emits a complete FastAPI application with SQLite, Jinja2 templates,
HTMX integration, stub auth, state machine enforcement, event handlers,
SSE streaming, and a role-aware navigation bar.
"""

import re
import textwrap
from datetime import datetime, timezone
from typing import Optional

from .ast_nodes import (
    Program, Application, Identity, Role, Content, Field, TypeExpr,
    AccessRule, StateMachine, Transition, EventRule, EventCondition,
    EventAction, UserStory, Directive, ShowPage, DisplayTable,
    ShowRelated, HighlightRows, AllowFilter, AllowSearch, SubscribeTo,
    AcceptInput, ValidateUnique, CreateAs, AfterSave, ShowChart,
    DisplayAggregation, NavBar, NavItem, ApiSection, ApiEndpoint, Stream,
)


def _snake(name: str) -> str:
    """Convert a display name to a Python/SQL identifier: 'unit cost' -> 'unit_cost'."""
    return re.sub(r'[^a-z0-9]+', '_', name.lower()).strip('_')


def _table(content_name: str) -> str:
    """Content name to SQL table name: 'stock levels' -> 'stock_levels'."""
    return _snake(content_name)


def _sql_type(te: TypeExpr) -> str:
    """Map a TypeExpr to a SQLite column type + constraints."""
    parts: list[str] = []
    if te.base_type == "text":
        parts.append("TEXT")
    elif te.base_type == "currency":
        parts.append("REAL")
    elif te.base_type == "whole_number":
        parts.append("INTEGER")
    elif te.base_type == "enum":
        vals = ", ".join(f"'{v}'" for v in te.enum_values)
        parts.append(f"TEXT CHECK({{col}} IN ({vals}))")
    elif te.base_type == "reference":
        parts.append("INTEGER")
    elif te.base_type == "automatic":
        parts.append("TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
    else:
        parts.append("TEXT")

    if te.required:
        parts.append("NOT NULL")
    if te.unique:
        parts.append("UNIQUE")
    if te.minimum is not None:
        parts.append(f"CHECK({{col}} >= {te.minimum})")

    return " ".join(parts)


class CodeGenerator:
    def __init__(self, program: Program, source_file: str = "unknown.an AWS-native runtime"):
        self.p = program
        self.source_file = source_file
        self.lines: list[str] = []
        # Map content name -> list of scope->verb mappings for access control
        self._access_map: dict[str, list[AccessRule]] = {}
        for c in self.p.contents:
            self._access_map[c.name] = c.access_rules
        # Map content_name -> StateMachine
        self._state_machines: dict[str, StateMachine] = {}
        for sm in self.p.state_machines:
            self._state_machines[sm.content_name] = sm
        # Collect page names from stories
        self._pages: dict[str, UserStory] = {}
        for story in self.p.stories:
            for d in story.directives:
                if isinstance(d, ShowPage):
                    self._pages[d.page_name] = story

    def generate(self) -> str:
        self._emit_header()
        self._emit_imports()
        self._emit_app_setup()
        self._emit_database()
        self._emit_identity()
        self._emit_event_bus()
        self._emit_models()
        self._emit_state_machines()
        self._emit_event_handlers()
        self._emit_api_routes()
        self._emit_sse_stream()
        self._emit_templates()
        self._emit_page_routes()
        self._emit_startup()
        self._emit_main()
        return "\n".join(self.lines)

    def _w(self, text: str = "") -> None:
        self.lines.append(text)

    def _wblock(self, text: str) -> None:
        self.lines.append(textwrap.dedent(text))

    # ── Header ──

    def _emit_header(self) -> None:
        now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        name = self.p.application.name if self.p.application else "an AWS-native Termin runtime App"
        self._wblock(f'''\
            # ============================================================
            # GENERATED BY TERMIN COMPILER v0.1
            # Source: {self.source_file}
            # Generated: {now}
            # Application: {name}
            # DO NOT EDIT — regenerate from .an AWS-native runtime source
            # ============================================================
        ''')

    # ── Imports ──

    def _emit_imports(self) -> None:
        self._wblock('''\
            import asyncio
            import json
            import os
            import sqlite3
            from contextlib import asynccontextmanager
            from datetime import datetime
            from pathlib import Path
            from typing import Optional

            import aiosqlite
            import uvicorn
            from fastapi import FastAPI, Request, Response, HTTPException, Depends, Form, Query
            from fastapi.responses import HTMLResponse, RedirectResponse, StreamingResponse
            from jinja2 import Environment, BaseLoader
            from pydantic import BaseModel, field_validator
        ''')

    # ── App Setup ──

    def _emit_app_setup(self) -> None:
        name = self.p.application.name if self.p.application else "an AWS-native Termin runtime App"
        desc = self.p.application.description if self.p.application else ""
        self._wblock(f'''\
            DB_PATH = "app.db"

            @asynccontextmanager
            async def lifespan(app):
                await init_db()
                yield

            app = FastAPI(title="{name}", description="{desc}", lifespan=lifespan)
        ''')

    # ── Database ──

    def _emit_database(self) -> None:
        self._wblock('''\
            async def get_db():
                db = await aiosqlite.connect(DB_PATH)
                db.row_factory = aiosqlite.Row
                await db.execute("PRAGMA foreign_keys = ON")
                return db

            async def init_db():
                db = await get_db()
                try:
        ''')

        for content in self.p.contents:
            table = _table(content.name)
            cols = ["id INTEGER PRIMARY KEY AUTOINCREMENT"]

            # Add status column if this content has a state machine
            if content.name in self._state_machines:
                sm = self._state_machines[content.name]
                cols.append(f"status TEXT NOT NULL DEFAULT '{sm.initial_state}'")

            for field in content.fields:
                col_name = _snake(field.name)
                sql_type = _sql_type(field.type_expr)
                # Replace {col} placeholder with actual column name
                sql_type = sql_type.replace("{col}", col_name)
                col_def = f"{col_name} {sql_type}"
                cols.append(col_def)

            # Foreign keys
            fk_clauses = []
            for field in content.fields:
                if field.type_expr.references:
                    col_name = _snake(field.name)
                    ref_table = _table(field.type_expr.references)
                    fk_clauses.append(
                        f"FOREIGN KEY ({col_name}) REFERENCES {ref_table}(id)"
                    )

            all_cols = cols + fk_clauses
            cols_sql = ",\n                ".join(all_cols)
            self._w(f'        await db.execute("""')
            self._w(f"            CREATE TABLE IF NOT EXISTS {table} (")
            self._w(f"                {cols_sql}")
            self._w(f"            )")
            self._w(f'        """)')
            self._w()

        self._w("        await db.commit()")
        self._w("    finally:")
        self._w("        await db.close()")
        self._w()

    # ── Identity / Auth ──

    def _emit_identity(self) -> None:
        roles_dict = {}
        for role in self.p.roles:
            roles_dict[role.name] = role.scopes

        self._w(f"ROLES = {repr(roles_dict)}")
        self._w()

        # Scope list for reference
        scopes = list(self.p.identity.scopes) if self.p.identity else []
        self._w(f"ALL_SCOPES = {repr(scopes)}")
        self._w()

        self._wblock('''\
            def get_current_user(request: Request) -> dict:
                """Get current user from cookie or default to first role."""
                role = request.cookies.get("termin_role", list(ROLES.keys())[0])
                if role not in ROLES:
                    role = list(ROLES.keys())[0]
                return {"role": role, "scopes": ROLES[role]}

            def require_scope(scope: str):
                """FastAPI dependency that checks the user has a required scope."""
                def checker(request: Request):
                    user = get_current_user(request)
                    if scope not in user["scopes"]:
                        raise HTTPException(status_code=403, detail=f"Requires scope: {scope}")
                    return user
                return checker
        ''')

    # ── Event Bus ──

    def _emit_event_bus(self) -> None:
        self._wblock('''\
            class EventBus:
                def __init__(self):
                    self._subscribers: list[asyncio.Queue] = []

                def subscribe(self) -> asyncio.Queue:
                    q: asyncio.Queue = asyncio.Queue()
                    self._subscribers.append(q)
                    return q

                def unsubscribe(self, q: asyncio.Queue):
                    self._subscribers.remove(q)

                async def publish(self, event: dict):
                    for q in self._subscribers:
                        await q.put(event)

            event_bus = EventBus()
        ''')

    # ── Pydantic Models ──

    def _emit_models(self) -> None:
        for content in self.p.contents:
            class_name = _snake(content.name).title().replace("_", "")
            self._w(f"class {class_name}Create(BaseModel):")
            has_fields = False
            for field in content.fields:
                if field.type_expr.base_type == "automatic":
                    continue
                fname = _snake(field.name)
                ptype = self._pydantic_type(field.type_expr)
                default = "" if field.type_expr.required else " = None"
                self._w(f"    {fname}: {ptype}{default}")
                has_fields = True
            if not has_fields:
                self._w("    pass")

            # Add validator for enum fields
            for field in content.fields:
                if field.type_expr.base_type == "enum":
                    fname = _snake(field.name)
                    vals = repr(field.type_expr.enum_values)
                    self._w()
                    self._w(f'    @field_validator("{fname}")')
                    self._w(f"    @classmethod")
                    self._w(f"    def validate_{fname}(cls, v):")
                    self._w(f"        if v is not None and v not in {vals}:")
                    self._w(f'            raise ValueError(f"{{v}} is not a valid {field.name}")')
                    self._w(f"        return v")

            self._w()

            # Update model (all fields optional)
            update_class = _snake(content.name).title().replace("_", "") + "Update"
            self._w(f"class {update_class}(BaseModel):")
            has_upd_fields = False
            for field in content.fields:
                if field.type_expr.base_type == "automatic":
                    continue
                fname = _snake(field.name)
                ptype = self._pydantic_type_optional(field.type_expr)
                self._w(f"    {fname}: {ptype} = None")
                has_upd_fields = True
            if not has_upd_fields:
                self._w("    pass")
            self._w()

    def _pydantic_type_optional(self, te: TypeExpr) -> str:
        base = self._pydantic_type(te)
        if base.startswith("Optional["):
            return base
        return f"Optional[{base}]"

    def _pydantic_type(self, te: TypeExpr) -> str:
        base = "str"
        if te.base_type == "whole_number":
            base = "int"
        elif te.base_type == "currency":
            base = "float"
        elif te.base_type == "reference":
            base = "int"
        elif te.base_type == "enum":
            base = "str"
        elif te.base_type == "text":
            base = "str"

        if not te.required:
            return f"Optional[{base}]"
        return base

    # ── State Machines ──

    def _emit_state_machines(self) -> None:
        if not self.p.state_machines:
            return

        self._w("# --- State Machine Transition Tables ---")
        self._w()
        self._w("STATE_MACHINES = {")
        for sm in self.p.state_machines:
            table = _table(sm.content_name)
            self._w(f'    "{table}": {{')
            self._w(f'        "initial": "{sm.initial_state}",')
            self._w(f'        "transitions": {{')
            for tr in sm.transitions:
                self._w(f'            ("{tr.from_state}", "{tr.to_state}"): "{tr.required_scope}",')
            self._w(f'        }},')
            self._w(f'    }},')
        self._w("}")
        self._w()

        self._wblock('''\
            async def do_state_transition(db, table: str, record_id: int, target_state: str, user: dict):
                """Attempt a state transition. Raises HTTPException on invalid transition."""
                if table not in STATE_MACHINES:
                    raise HTTPException(status_code=400, detail=f"No state machine for {table}")

                sm = STATE_MACHINES[table]
                cursor = await db.execute(f"SELECT status FROM {table} WHERE id = ?", (record_id,))
                row = await cursor.fetchone()
                if not row:
                    raise HTTPException(status_code=404, detail="Record not found")

                current = row["status"]
                key = (current, target_state)
                if key not in sm["transitions"]:
                    raise HTTPException(
                        status_code=409,
                        detail=f"Cannot transition from '{current}' to '{target_state}'"
                    )

                required_scope = sm["transitions"][key]
                if required_scope not in user["scopes"]:
                    raise HTTPException(
                        status_code=403,
                        detail=f"Transition requires scope: {required_scope}"
                    )

                await db.execute(f"UPDATE {table} SET status = ? WHERE id = ?", (target_state, record_id))
                await db.commit()
                await event_bus.publish({"type": f"{table}_updated", "id": record_id, "status": target_state})
                return {"id": record_id, "status": target_state}
        ''')

    # ── Event Handlers ──

    def _emit_event_handlers(self) -> None:
        if not self.p.events:
            self._w("async def run_event_handlers(db, content_name: str, trigger: str, record: dict):")
            self._w("    pass")
            self._w()
            return

        self._w("async def run_event_handlers(db, content_name: str, trigger: str, record: dict):")
        self._w('    """Execute event rules that match the content mutation."""')

        for event in self.p.events:
            # Event content_name may be singular ("stock level") — find the actual Content
            content_table = _table(event.content_name)
            # Also try the plural form to match against defined Content names
            for c in self.p.contents:
                if _table(c.name) == content_table or _table(c.singular) == content_table:
                    content_table = _table(c.name)
                    break
            self._w(f'    if content_name == "{content_table}" and trigger == "{event.trigger}":')

            if event.condition:
                f1 = _snake(event.condition.field1)
                f2 = _snake(event.condition.field2)
                if event.condition.operator == "at or below":
                    self._w(f'        if record.get("{f1}", 0) <= record.get("{f2}", 0):')
                else:
                    self._w(f'        if True:  # condition: {event.condition.operator}')

                if event.action:
                    # Find the actual Content for the target
                    target_table = _table(event.action.create_content + "s")
                    target_content = None
                    for c in self.p.contents:
                        if c.singular == event.action.create_content or c.name == event.action.create_content:
                            target_table = _table(c.name)
                            target_content = c
                            break

                    # Find source content for field mapping
                    source_content = None
                    for c in self.p.contents:
                        if _table(c.name) == content_table:
                            source_content = c
                            break
                    source_cols = {_snake(f.name) for f in source_content.fields} if source_content else set()

                    # Map event field names to target columns and source record keys
                    target_cols = []
                    source_keys = []
                    for fname in event.action.fields:
                        target_col = _snake(fname)
                        target_cols.append(target_col)
                        # If the target col name exists in the source record, use it directly
                        if target_col in source_cols:
                            source_keys.append(target_col)
                        else:
                            # Try to find a matching source field by partial name
                            matched = False
                            for sc in source_cols:
                                if fname.lower() in sc or sc in _snake(fname):
                                    source_keys.append(sc)
                                    matched = True
                                    break
                            if not matched:
                                source_keys.append(target_col)

                    cols = ", ".join(target_cols)
                    placeholders = ", ".join(["?"] * len(target_cols))
                    values = ", ".join(f'record.get("{sk}", "")' for sk in source_keys)

                    self._w(f'            await db.execute(')
                    self._w(f'                "INSERT INTO {target_table} ({cols}) VALUES ({placeholders})",')
                    self._w(f'                ({values},)')
                    self._w(f'            )')
                    self._w(f'            await db.commit()')
                    self._w(f'            await event_bus.publish({{"type": "{target_table}_created"}})')
            else:
                if event.action:
                    # Find the actual Content for the target
                    target_table = _table(event.action.create_content + "s")
                    for c in self.p.contents:
                        if c.singular == event.action.create_content or c.name == event.action.create_content:
                            target_table = _table(c.name)
                            break
                    self._w(f'        pass  # TODO: unconditional event action')

        self._w()

    # ── API Routes ──

    def _emit_api_routes(self) -> None:
        if not self.p.api:
            return

        base = self.p.api.base_path.rstrip("/")

        for ep in self.p.api.endpoints:
            full_path = base + ep.path
            method = ep.method.lower()

            # Determine which content this endpoint relates to
            content, content_obj = self._infer_content_for_path(ep.path)
            if not content:
                continue

            table = _table(content)

            # Determine the operation type from method + path pattern
            has_param = "{" in ep.path
            is_transition = any(
                word in ep.description.lower()
                for word in ["transition", "activate", "discontinue", "acknowledge"]
            )

            if is_transition:
                self._emit_transition_route(method, full_path, ep, table, content)
            elif method == "get" and not has_param:
                self._emit_list_route(full_path, ep, table, content, content_obj)
            elif method == "get" and has_param:
                self._emit_get_route(full_path, ep, table, content, content_obj)
            elif method == "post" and not has_param:
                self._emit_create_route(full_path, ep, table, content, content_obj)
            elif method == "put" and has_param:
                self._emit_update_route(full_path, ep, table, content, content_obj)
            elif method == "delete" and has_param:
                self._emit_delete_route(full_path, ep, table, content, content_obj)

    def _infer_content_for_path(self, path: str) -> tuple[Optional[str], Optional[Content]]:
        """Infer which Content a path relates to based on the first segment."""
        # /products -> "products", /stock-levels -> "stock levels", /alerts -> "reorder alerts"
        parts = path.strip("/").split("/")
        segment = parts[0] if parts else ""
        segment_norm = segment.replace("-", " ")

        for c in self.p.contents:
            if _snake(c.name) == _snake(segment_norm):
                return c.name, c
            # Try partial match: "alerts" -> "reorder alerts"
            if segment_norm in c.name or c.name.endswith(segment_norm):
                return c.name, c

        return None, None

    def _view_scope(self, content_name: str) -> Optional[str]:
        for rule in self._access_map.get(content_name, []):
            if "view" in rule.verbs:
                return rule.scope
        return None

    def _create_scope(self, content_name: str) -> Optional[str]:
        for rule in self._access_map.get(content_name, []):
            if "create" in rule.verbs or "create or update" in rule.verbs:
                return rule.scope
        return None

    def _update_scope(self, content_name: str) -> Optional[str]:
        for rule in self._access_map.get(content_name, []):
            if "update" in rule.verbs or "create or update" in rule.verbs:
                return rule.scope
        return None

    def _delete_scope(self, content_name: str) -> Optional[str]:
        for rule in self._access_map.get(content_name, []):
            if "delete" in rule.verbs:
                return rule.scope
        return None

    def _emit_list_route(self, path, ep, table, content_name, content_obj):
        scope = self._view_scope(content_name)
        scope_dep = f', user=Depends(require_scope("{scope}"))' if scope else ""
        self._w(f'@app.get("{path}")')
        self._w(f"async def list_{table}(request: Request{scope_dep}):")
        self._w(f'    db = await get_db()')
        self._w(f'    try:')
        self._w(f'        cursor = await db.execute("SELECT * FROM {table}")')
        self._w(f'        rows = await cursor.fetchall()')
        self._w(f'        return [{{"id": r["id"], **dict(r)}} for r in rows]')
        self._w(f'    finally:')
        self._w(f'        await db.close()')
        self._w()

    def _emit_get_route(self, path, ep, table, content_name, content_obj):
        scope = self._view_scope(content_name)
        scope_dep = f', user=Depends(require_scope("{scope}"))' if scope else ""
        # Determine param name from path
        param = re.search(r'\{(\w+)\}', path)
        param_name = param.group(1) if param else "id"

        # Determine lookup column
        lookup_col = "id"
        if content_obj:
            for f in content_obj.fields:
                if f.type_expr.unique:
                    lookup_col = _snake(f.name)
                    break

        self._w(f'@app.get("{path}")')
        self._w(f"async def get_{table}_by_{param_name}({param_name}: str{scope_dep}):")
        self._w(f'    db = await get_db()')
        self._w(f'    try:')
        self._w(f'        cursor = await db.execute("SELECT * FROM {table} WHERE {lookup_col} = ?", ({param_name},))')
        self._w(f'        row = await cursor.fetchone()')
        self._w(f'        if not row:')
        self._w(f'            raise HTTPException(status_code=404, detail="Not found")')
        self._w(f'        return dict(row)')
        self._w(f'    finally:')
        self._w(f'        await db.close()')
        self._w()

    def _emit_create_route(self, path, ep, table, content_name, content_obj):
        scope = self._create_scope(content_name)
        scope_dep = f', user=Depends(require_scope("{scope}"))' if scope else ""
        model_name = _snake(content_name).title().replace("_", "") + "Create"

        self._w(f'@app.post("{path}", status_code=201)')
        self._w(f"async def create_{table}(data: {model_name}{scope_dep}):")
        self._w(f'    db = await get_db()')
        self._w(f'    try:')
        self._w(f'        d = data.model_dump(exclude_none=True)')

        # Add initial state if state machine exists
        if content_name in self._state_machines:
            sm = self._state_machines[content_name]
            self._w(f'        d.setdefault("status", "{sm.initial_state}")')

        cols = ", ".join(f'"{_snake(f.name)}"' for f in content_obj.fields if f.type_expr.base_type != "automatic")
        self._w(f'        columns = [k for k in d.keys()]')
        self._w(f'        placeholders = ", ".join(["?"] * len(columns))')
        self._w(f'        col_str = ", ".join(columns)')
        self._w(f'        values = [d[k] for k in columns]')
        self._w(f'        try:')
        self._w(f'            cursor = await db.execute(f"INSERT INTO {table} ({{col_str}}) VALUES ({{placeholders}})", values)')
        self._w(f'        except sqlite3.IntegrityError as e:')
        self._w(f'            raise HTTPException(status_code=409, detail=str(e))')
        self._w(f'        await db.commit()')
        self._w(f'        record_id = cursor.lastrowid')

        # Fetch created record for event handlers
        self._w(f'        cursor2 = await db.execute("SELECT * FROM {table} WHERE id = ?", (record_id,))')
        self._w(f'        record = dict(await cursor2.fetchone())')
        self._w(f'        await run_event_handlers(db, "{table}", "created", record)')
        self._w(f'        await event_bus.publish({{"type": "{table}_created", "id": record_id}})')
        self._w(f'        return {{"id": record_id, **record}}')
        self._w(f'    finally:')
        self._w(f'        await db.close()')
        self._w()

    def _emit_update_route(self, path, ep, table, content_name, content_obj):
        scope = self._update_scope(content_name)
        scope_dep = f', user=Depends(require_scope("{scope}"))' if scope else ""
        model_name = _snake(content_name).title().replace("_", "") + "Update"
        param = re.search(r'\{(\w+)\}', path)
        param_name = param.group(1) if param else "id"

        lookup_col = "id"
        if content_obj:
            for f in content_obj.fields:
                if f.type_expr.unique:
                    lookup_col = _snake(f.name)
                    break

        self._w(f'@app.put("{path}")')
        self._w(f"async def update_{table}({param_name}: str, data: {model_name}{scope_dep}):")
        self._w(f'    db = await get_db()')
        self._w(f'    try:')
        self._w(f'        d = data.model_dump(exclude_unset=True)')
        self._w(f'        if not d:')
        self._w(f'            raise HTTPException(status_code=422, detail="No fields to update")')
        self._w(f'        set_clause = ", ".join(f"{{k}} = ?" for k in d.keys())')
        self._w(f'        values = list(d.values()) + [{param_name}]')
        self._w(f'        await db.execute(f"UPDATE {table} SET {{set_clause}} WHERE {lookup_col} = ?", values)')
        self._w(f'        await db.commit()')

        # Fetch updated record for event handlers
        self._w(f'        cursor = await db.execute("SELECT * FROM {table} WHERE {lookup_col} = ?", ({param_name},))')
        self._w(f'        row = await cursor.fetchone()')
        self._w(f'        if not row:')
        self._w(f'            raise HTTPException(status_code=404, detail="Not found")')
        self._w(f'        record = dict(row)')
        self._w(f'        await run_event_handlers(db, "{table}", "updated", record)')
        self._w(f'        await event_bus.publish({{"type": "{table}_updated", "id": row["id"]}})')
        self._w(f'        return record')
        self._w(f'    finally:')
        self._w(f'        await db.close()')
        self._w()

    def _emit_delete_route(self, path, ep, table, content_name, content_obj):
        scope = self._delete_scope(content_name)
        scope_dep = f', user=Depends(require_scope("{scope}"))' if scope else ""
        param = re.search(r'\{(\w+)\}', path)
        param_name = param.group(1) if param else "id"

        lookup_col = "id"
        if content_obj:
            for f in content_obj.fields:
                if f.type_expr.unique:
                    lookup_col = _snake(f.name)
                    break

        self._w(f'@app.delete("{path}")')
        self._w(f"async def delete_{table}({param_name}: str{scope_dep}):")
        self._w(f'    db = await get_db()')
        self._w(f'    try:')
        self._w(f'        cursor = await db.execute("SELECT * FROM {table} WHERE {lookup_col} = ?", ({param_name},))')
        self._w(f'        row = await cursor.fetchone()')
        self._w(f'        if not row:')
        self._w(f'            raise HTTPException(status_code=404, detail="Not found")')
        self._w(f'        await db.execute("DELETE FROM {table} WHERE {lookup_col} = ?", ({param_name},))')
        self._w(f'        await db.commit()')
        self._w(f'        await event_bus.publish({{"type": "{table}_deleted", "id": row["id"]}})')
        self._w(f'        return {{"deleted": True}}')
        self._w(f'    finally:')
        self._w(f'        await db.close()')
        self._w()

    def _emit_transition_route(self, method, path, ep, table, content_name):
        # Infer target state from path suffix
        parts = path.rstrip("/").split("/")
        action = parts[-1]  # "activate", "discontinue", "start", "resolve", etc.

        # Build a map from action words to actual state names using the
        # API endpoint descriptions and the state machine transitions.
        # Common patterns: "activate" -> "active", "discontinue" -> "discontinued"
        # For multi-word states: match the endpoint action to the closest
        # transition target_state in the state machine.
        target_state = action  # fallback
        if content_name in self._state_machines:
            sm = self._state_machines[content_name]
            # Try exact match first
            if action in sm.states:
                target_state = action
            else:
                # Try common verb->state mappings
                verb_map = {
                    "activate": "active",
                    "discontinue": "discontinued",
                    "acknowledge": "acknowledged",
                    "close": "closed",
                    "resolve": "resolved",
                    "reopen": "in progress",
                    "start": "in progress",
                    "wait": "waiting on customer",
                    "complete": "completed",
                    "cancel": "cancelled",
                    "approve": "approved",
                    "reject": "rejected",
                    "archive": "archived",
                    "suspend": "suspended",
                    "resume": "active",
                }
                if action in verb_map and verb_map[action] in sm.states:
                    target_state = verb_map[action]
                else:
                    # Fuzzy match: find states that start with or contain the action
                    for state in sm.states:
                        if state.startswith(action) or action.startswith(state.split()[0]):
                            target_state = state
                            break
                    # Also try matching by the API description
                    if ep and ep.description:
                        desc_lower = ep.description.lower()
                        for state in sm.states:
                            if state in desc_lower:
                                target_state = state
                                break

        param = re.search(r'\{(\w+)\}', path)
        param_name = param.group(1) if param else "id"

        lookup_col = "id"
        content_obj = next((c for c in self.p.contents if c.name == content_name), None)
        if content_obj:
            for f in content_obj.fields:
                if f.type_expr.unique:
                    lookup_col = _snake(f.name)
                    break

        route_name = f"transition_{table}_{_snake(action)}"
        self._w(f'@app.{method}("{path}")')
        self._w(f"async def {route_name}({param_name}: str, user=Depends(get_current_user)):")
        self._w(f'    db = await get_db()')
        self._w(f'    try:')
        self._w(f'        cursor = await db.execute("SELECT id, status FROM {table} WHERE {lookup_col} = ?", ({param_name},))')
        self._w(f'        row = await cursor.fetchone()')
        self._w(f'        if not row:')
        self._w(f'            raise HTTPException(status_code=404, detail="Not found")')
        self._w(f'        return await do_state_transition(db, "{table}", row["id"], "{target_state}", user)')
        self._w(f'    finally:')
        self._w(f'        await db.close()')
        self._w()

    # ── SSE Stream ──

    def _emit_sse_stream(self) -> None:
        for stream in self.p.streams:
            path = stream.path
            self._w(f'@app.get("{path}")')
            self._w(f"async def sse_stream(request: Request):")
            self._w(f"    async def generate():")
            self._w(f"        q = event_bus.subscribe()")
            self._w(f"        try:")
            self._w(f"            while True:")
            self._w(f"                event = await q.get()")
            self._w(f'                yield f"data: {{json.dumps(event)}}\\n\\n"')
            self._w(f"        except asyncio.CancelledError:")
            self._w(f"            event_bus.unsubscribe(q)")
            self._w(f'    return StreamingResponse(generate(), media_type="text/event-stream")')
            self._w()

    # ── Templates ──

    def _emit_templates(self) -> None:
        self._w("# --- Jinja2 Template Environment ---")
        self._w("jinja_env = Environment(loader=BaseLoader(), autoescape=True)")
        self._w()

        # Base template
        app_name = self.p.application.name if self.p.application else "App"
        nav_html = self._build_nav_html()

        base_template = f'''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{app_name} - {{{{ page_title }}}}</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://unpkg.com/htmx.org@1.9.10"></script>
    <script src="https://unpkg.com/htmx.org@1.9.10/dist/ext/sse.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body class="bg-gray-50 min-h-screen">
    <nav class="bg-white shadow mb-6">
        <div class="max-w-7xl mx-auto px-4 py-3 flex items-center justify-between">
            <div class="flex items-center space-x-6">
                <span class="text-lg font-bold text-indigo-600">{app_name}</span>
                {nav_html}
            </div>
            <form method="post" action="/set-role" class="flex items-center space-x-2">
                <label class="text-sm text-gray-600">Role:</label>
                <select name="role" onchange="this.form.submit()" class="text-sm border rounded px-2 py-1">
                    {{% for rname in roles %}}
                    <option value="{{{{ rname }}}}" {{% if rname == current_role %}}selected{{% endif %}}>{{{{ rname|title }}}}</option>
                    {{% endfor %}}
                </select>
            </form>
        </div>
    </nav>
    <main class="max-w-7xl mx-auto px-4">
        {{{{ content|safe }}}}
    </main>
</body>
</html>'''

        self._w(f'BASE_TEMPLATE = jinja_env.from_string({repr(base_template.strip())})')
        self._w()

        # Role switcher endpoint
        self._wblock('''\
            @app.post("/set-role")
            async def set_role(role: str = Form(...)):
                response = RedirectResponse(url="/", status_code=303)
                response.set_cookie("termin_role", role)
                return response
        ''')

        # Generate page templates
        for story in self.p.stories:
            self._emit_page_template(story)

    def _build_nav_html(self) -> str:
        if not self.p.navigation:
            return ""

        items_html = []
        for item in self.p.navigation.items:
            slug = _snake(item.page_name)
            href = f"/{slug}"

            # Visibility check
            if "all" in item.visible_to:
                vis = ""
            else:
                role_checks = " or ".join(
                    f'current_role == "{r}"' if r in [role.name for role in self.p.roles]
                    else f'"{r}" in current_role'
                    for r in item.visible_to
                )
                vis = f'{{% if {role_checks} %}}'

            badge_html = ""
            if item.badge:
                badge_html = (
                    f' <span class="ml-1 bg-red-500 text-white text-xs rounded-full px-2 py-0.5">'
                    f'{{{{ badge_{_snake(item.label)} }}}}</span>'
                )

            link = f'<a href="{href}" class="text-gray-700 hover:text-indigo-600">{item.label}{badge_html}</a>'
            if vis:
                link = f"{vis}{link}{{% endif %}}"
            items_html.append(link)

        return "\n                ".join(items_html)

    def _emit_page_template(self, story: UserStory) -> None:
        page_name = None
        for d in story.directives:
            if isinstance(d, ShowPage):
                page_name = d.page_name
                break
        if not page_name:
            return

        slug = _snake(page_name)
        template_parts = [f'<h1 class="text-2xl font-bold mb-4">{page_name}</h1>']

        for d in story.directives:
            if isinstance(d, DisplayTable):
                template_parts.append(self._gen_table_html(d, story))
            elif isinstance(d, AcceptInput):
                template_parts.append(self._gen_form_html(d, story))
            elif isinstance(d, DisplayAggregation):
                template_parts.append(self._gen_aggregation_html(d))
            elif isinstance(d, ShowChart):
                template_parts.append(self._gen_chart_html(d))

        template_content = "\n".join(template_parts)
        var_name = f"TEMPLATE_{slug.upper()}"
        self._w(f'{var_name} = jinja_env.from_string({repr(template_content)})')
        self._w()

    def _gen_table_html(self, d: DisplayTable, story: UserStory) -> str:
        table = _table(d.content_name)
        cols = d.columns if d.columns else ["id"]

        # Check for highlight, filter, search directives
        highlight = None
        filters = None
        search = None
        subscribe = None
        show_related = None
        for dir_ in story.directives:
            if isinstance(dir_, HighlightRows):
                highlight = dir_
            elif isinstance(dir_, AllowFilter):
                filters = dir_
            elif isinstance(dir_, AllowSearch):
                search = dir_
            elif isinstance(dir_, SubscribeTo):
                subscribe = dir_
            elif isinstance(dir_, ShowRelated):
                show_related = dir_

        parts = []

        # Filter form
        if filters:
            # Look up the content to find field types
            content_obj = None
            for c in self.p.contents:
                if c.name == d.content_name:
                    content_obj = c
                    break

            parts.append('<form method="get" class="mb-4 flex gap-4 items-end">')
            for f in filters.fields:
                fname = _snake(f)
                dfl = "{{" + f" filters.{fname}|default('') " + "}}"

                # Determine if this field should be a dropdown
                field_obj = None
                if content_obj:
                    for cf in content_obj.fields:
                        if _snake(cf.name) == fname:
                            field_obj = cf
                            break

                # "status" field -> get values from state machine
                if fname == "status" and content_obj and content_obj.name in self._state_machines:
                    sm = self._state_machines[content_obj.name]
                    parts.append(f'  <div>')
                    parts.append(f'    <label class="block text-sm text-gray-600">{f}</label>')
                    parts.append(f'    <select name="{fname}" class="border rounded px-2 py-1 text-sm">')
                    parts.append(f'      <option value="">All</option>')
                    for state in sm.states:
                        sel = "{{" + f' "selected" if filters.{fname}|default("") == "{state}" else "" ' + "}}"
                        parts.append(f'      <option value="{state}" {sel}>{state}</option>')
                    parts.append(f'    </select>')
                    parts.append(f'  </div>')
                # Enum field -> dropdown with enum values
                elif field_obj and field_obj.type_expr.base_type == "enum":
                    parts.append(f'  <div>')
                    parts.append(f'    <label class="block text-sm text-gray-600">{f}</label>')
                    parts.append(f'    <select name="{fname}" class="border rounded px-2 py-1 text-sm">')
                    parts.append(f'      <option value="">All</option>')
                    for val in field_obj.type_expr.enum_values:
                        sel = "{{" + f' "selected" if filters.{fname}|default("") == "{val}" else "" ' + "}}"
                        parts.append(f'      <option value="{val}" {sel}>{val}</option>')
                    parts.append(f'    </select>')
                    parts.append(f'  </div>')
                # "warehouse" or other text fields used across stock_levels -> populate from distinct values
                elif fname == "warehouse":
                    parts.append(f'  <div>')
                    parts.append(f'    <label class="block text-sm text-gray-600">{f}</label>')
                    parts.append(f'    <select name="{fname}" class="border rounded px-2 py-1 text-sm">')
                    parts.append(f'      <option value="">All</option>')
                    parts.append(f'      {{% for wh in warehouse_options %}}')
                    sel = "{{" + f' "selected" if filters.{fname}|default("") == wh else "" ' + "}}"
                    parts.append(f'      <option value="{{{{ wh }}}}" {sel}>{{{{ wh }}}}</option>')
                    parts.append(f'      {{% endfor %}}')
                    parts.append(f'    </select>')
                    parts.append(f'  </div>')
                else:
                    # Fallback: plain text input
                    parts.append(f'  <div>')
                    parts.append(f'    <label class="block text-sm text-gray-600">{f}</label>')
                    parts.append(f'    <input type="text" name="{fname}" value="{dfl}" class="border rounded px-2 py-1 text-sm">')
                    parts.append(f'  </div>')
            parts.append('  <button type="submit" class="bg-indigo-600 text-white px-4 py-1 rounded text-sm">Filter</button>')
            parts.append('</form>')

        # Search form
        if search:
            parts.append('<form method="get" class="mb-4">')
            fields_str = " or ".join(search.fields)
            q_dfl = "{{ q|default('') }}"
            parts.append(f'  <input type="text" name="q" value="{q_dfl}" placeholder="Search by {fields_str}..." class="border rounded px-3 py-2 w-64 text-sm">')
            parts.append('  <button type="submit" class="bg-gray-200 px-3 py-2 rounded text-sm ml-2">Search</button>')
            parts.append('</form>')

        # SSE wrapper
        sse_attrs = ""
        if subscribe:
            stream_path = self.p.streams[0].path if self.p.streams else "/api/v1/stream"
            sse_attrs = f' hx-ext="sse" sse-connect="{stream_path}" sse-swap="message" hx-swap="innerHTML"'

        parts.append(f'<div id="{table}-table"{sse_attrs}>')
        parts.append('<table class="w-full bg-white shadow rounded overflow-hidden">')
        parts.append('  <thead class="bg-gray-100">')
        parts.append('    <tr>')
        for col in cols:
            parts.append(f'      <th class="px-4 py-2 text-left text-sm font-medium text-gray-600">{col}</th>')
        if show_related:
            parts.append(f'      <th class="px-4 py-2 text-left text-sm font-medium text-gray-600">{show_related.related_content}</th>')
        parts.append('    </tr>')
        parts.append('  </thead>')
        parts.append('  <tbody>')
        parts.append(f'    {{% for item in items %}}')

        # Row highlight
        if highlight:
            f1 = _snake(highlight.field)
            f2 = _snake(highlight.threshold_field)
            # Use Jinja2 default filter to handle missing fields gracefully
            parts.append(f'    <tr class="{{% set v1 = item["{f1}"]|default(none) %}}{{% set v2 = item["{f2}"]|default(none) %}}{{% if v1 is not none and v2 is not none and v1 <= v2 %}}bg-red-50{{% else %}}bg-white{{% endif %}} border-t">')
        else:
            parts.append('    <tr class="border-t">')

        for col in cols:
            col_key = _snake(col)
            col_dfl = "{{" + f" item.{col_key}|default('') " + "}}"
            parts.append(f'      <td class="px-4 py-2 text-sm">{col_dfl}</td>')

        if show_related:
            rel_dfl = "{{ item.related|default('') }}"
            parts.append(f'      <td class="px-4 py-2 text-sm">{rel_dfl}</td>')

        parts.append('    </tr>')
        parts.append('    {% endfor %}')
        parts.append('  </tbody>')
        parts.append('</table>')
        parts.append('</div>')

        return "\n".join(parts)

    def _gen_form_html(self, d: AcceptInput, story: UserStory) -> str:
        # Determine the content this form creates (pick the one with most matching fields)
        content_obj = None
        best_match_count = 0
        for c in self.p.contents:
            match_count = sum(
                1 for f in d.fields
                if _snake(f) in {_snake(cf.name) for cf in c.fields}
            )
            if match_count > best_match_count:
                best_match_count = match_count
                content_obj = c

        if not content_obj:
            return '<p>Form configuration error</p>'

        table = _table(content_obj.name)
        api_base = self.p.api.base_path.rstrip("/") if self.p.api else "/api/v1"

        # Check for validation and create-as directives
        validate_field = None
        initial_state = None
        for dir_ in story.directives:
            if isinstance(dir_, ValidateUnique):
                validate_field = dir_.field
            elif isinstance(dir_, CreateAs):
                initial_state = dir_.initial_state

        parts = []
        parts.append(f'<form method="post" action="/{_snake(story.directives[0].page_name) if isinstance(story.directives[0], ShowPage) else table}" class="bg-white shadow rounded p-6 max-w-lg">')

        for fname in d.fields:
            col = _snake(fname)
            # Find field definition
            field_obj = None
            for cf in content_obj.fields:
                if _snake(cf.name) == col:
                    field_obj = cf
                    break

            input_type = "text"
            extra_attrs = ""
            if field_obj:
                if field_obj.type_expr.base_type == "currency":
                    input_type = "number"
                    extra_attrs = ' step="0.01"'
                elif field_obj.type_expr.base_type == "whole_number":
                    input_type = "number"
                    if field_obj.type_expr.minimum is not None:
                        extra_attrs = f' min="{field_obj.type_expr.minimum}"'
                elif field_obj.type_expr.base_type == "enum":
                    # Render as select
                    parts.append(f'  <div class="mb-4">')
                    parts.append(f'    <label class="block text-sm font-medium text-gray-700 mb-1">{fname}</label>')
                    parts.append(f'    <select name="{col}" class="w-full border rounded px-3 py-2">')
                    parts.append(f'      <option value="">Select...</option>')
                    for val in field_obj.type_expr.enum_values:
                        parts.append(f'      <option value="{val}">{val}</option>')
                    parts.append(f'    </select>')
                    parts.append(f'  </div>')
                    continue

                if field_obj.type_expr.required:
                    extra_attrs += " required"

                # Foreign key reference -> render as dropdown populated from referenced table
                if field_obj.type_expr.references:
                    ref_content = field_obj.type_expr.references
                    ref_table = _table(ref_content)
                    # Find display field: prefer 'name', fall back to first unique text field, then 'id'
                    ref_obj = None
                    for c in self.p.contents:
                        if c.name == ref_content:
                            ref_obj = c
                            break
                    # Find display and unique fields from the referenced content
                    display_col = "id"
                    unique_col = None
                    if ref_obj:
                        for rf in ref_obj.fields:
                            if rf.type_expr.unique and rf.type_expr.base_type == "text":
                                unique_col = _snake(rf.name)
                            if _snake(rf.name) == "name":
                                display_col = "name"
                        if not unique_col and display_col == "id":
                            # Fall back to first text field
                            for rf in ref_obj.fields:
                                if rf.type_expr.base_type == "text":
                                    display_col = _snake(rf.name)
                                    break
                    # Build option label: "Name (SKU)" or just "Name"
                    if unique_col and unique_col != display_col:
                        option_label = f'{{{{ item.{display_col} }}}} ({{{{ item.{unique_col} }}}})'
                    else:
                        option_label = f'{{{{ item.{display_col} }}}}'
                    parts.append(f'  <div class="mb-4">')
                    parts.append(f'    <label class="block text-sm font-medium text-gray-700 mb-1">{fname}</label>')
                    parts.append(f'    <select name="{col}" class="w-full border rounded px-3 py-2"{extra_attrs}>')
                    parts.append(f'      <option value="">Select {ref_content}...</option>')
                    parts.append(f'      {{% for item in {ref_table}_list %}}')
                    parts.append(f'      <option value="{{{{ item.id }}}}">{option_label}</option>')
                    parts.append(f'      {{% endfor %}}')
                    parts.append(f'    </select>')
                    parts.append(f'  </div>')
                    continue

            parts.append(f'  <div class="mb-4">')
            parts.append(f'    <label class="block text-sm font-medium text-gray-700 mb-1">{fname}</label>')
            parts.append(f'    <input type="{input_type}" name="{col}" class="w-full border rounded px-3 py-2"{extra_attrs}>')
            parts.append(f'  </div>')

        parts.append(f'  <input type="hidden" name="edit_id" value="">')
        parts.append(f'  <button type="submit" class="bg-indigo-600 text-white px-6 py-2 rounded hover:bg-indigo-700">Save</button>')
        parts.append(f'</form>')

        # Check if story already has a DisplayTable — if so, skip auto-generated table
        has_display_table = any(isinstance(dir_, DisplayTable) for dir_ in story.directives)
        if not has_display_table:
            # Auto-generate existing records table below the form
            # Determine display columns: form fields + id + status if state machine
            display_cols = ["id"] + [_snake(f) for f in d.fields]
            if content_obj.name in self._state_machines and "status" not in display_cols:
                display_cols.append("status")

            # Add "created_at" if present
            for cf in content_obj.fields:
                if cf.type_expr.base_type == "automatic" and _snake(cf.name) not in display_cols:
                    display_cols.append(_snake(cf.name))

            slug = _snake(story.directives[0].page_name) if isinstance(story.directives[0], ShowPage) else table

            parts.append(f'<h2 class="text-xl font-semibold mt-8 mb-4">Existing {content_obj.name.title()}</h2>')
            parts.append(f'<div class="w-full bg-white shadow rounded overflow-hidden">')
            parts.append(f'<table class="w-full">')
            parts.append(f'  <thead class="bg-gray-100">')
            parts.append(f'    <tr>')
            for col in display_cols:
                parts.append(f'      <th class="px-4 py-2 text-left text-sm font-medium text-gray-600">{col.replace("_", " ")}</th>')
            parts.append(f'      <th class="px-4 py-2 text-left text-sm font-medium text-gray-600">actions</th>')
            parts.append(f'    </tr>')
            parts.append(f'  </thead>')
            parts.append(f'  <tbody>')
            parts.append(f'    {{% for row in {table}_rows %}}')
            parts.append(f'    <tr class="border-t">')
            for col in display_cols:
                parts.append(f'      <td class="px-4 py-2 text-sm">{{{{ row.{col}|default("") }}}}</td>')
            # Edit button: fills form fields via JS
            js_fill_parts = []
            for fname in d.fields:
                col = _snake(fname)
                js_fill_parts.append(f"""el=document.querySelector('[name="{col}"]');if(el){{if(el.tagName==="SELECT"){{for(var i=0;i<el.options.length;i++)if(el.options[i].value==row.{col})el.selectedIndex=i;}}else el.value=row.{col};}}""")
            js_fill = "".join(js_fill_parts)
            js_edit = f"var row={{{{row|tojson}}}};document.querySelector('[name=\\'edit_id\\']').value=row.id;{js_fill}window.scrollTo(0,0);return false;"
            parts.append(f'      <td class="px-4 py-2 text-sm">')
            parts.append(f'        <a href="#" onclick=\'{js_edit}\' class="text-indigo-600 hover:underline mr-3">Edit</a>')
            parts.append(f'        <form method="post" action="/{slug}/delete/{{{{ row.id }}}}" class="inline" onsubmit="return confirm(\'Delete this record?\')">')
            parts.append(f'          <button type="submit" class="text-red-600 hover:underline">Delete</button>')
            parts.append(f'        </form>')
            parts.append(f'      </td>')
            parts.append(f'    </tr>')
            parts.append(f'    {{% endfor %}}')
            parts.append(f'  </tbody>')
            parts.append(f'</table>')
            parts.append(f'</div>')

        return "\n".join(parts)

    def _gen_aggregation_html(self, d: DisplayAggregation) -> str:
        slug = _snake(d.description)[:30]
        return (
            f'<div class="bg-white shadow rounded p-4 mb-4">'
            f'  <div class="text-sm text-gray-600">{d.description}</div>'
            f'  <div class="text-2xl font-bold mt-1">{{{{ {slug} }}}}</div>'
            f'</div>'
        )

    def _gen_chart_html(self, d: ShowChart) -> str:
        chart_id = _snake(d.content_name) + "_chart"
        return (
            f'<div class="bg-white shadow rounded p-4 mb-4">'
            f'  <canvas id="{chart_id}" height="200"></canvas>'
            f'</div>'
            f'<script>'
            f'fetch("/api/chart-data/{_snake(d.content_name)}")'
            f'.then(r=>r.json()).then(data=>{{'
            f'new Chart(document.getElementById("{chart_id}"),{{'
            f'type:"line",data:{{labels:data.labels,datasets:[{{label:"{d.content_name}",data:data.values,borderColor:"rgb(79,70,229)",tension:0.1}}]}}'
            f'}});}});'
            f'</script>'
        )

    # ── Page Routes ──

    def _emit_page_routes(self) -> None:
        # Home route -> redirect to first page
        first_page = None
        for story in self.p.stories:
            for d in story.directives:
                if isinstance(d, ShowPage):
                    first_page = d.page_name
                    break
            if first_page:
                break

        if first_page:
            self._w(f'@app.get("/", response_class=HTMLResponse)')
            self._w(f"async def home(request: Request):")
            self._w(f'    return RedirectResponse(url="/{_snake(first_page)}")')
            self._w()

        for story in self.p.stories:
            self._emit_page_route(story)

    def _emit_page_route(self, story: UserStory) -> None:
        page_name = None
        display_table = None
        accept_input = None
        filters_directive = None
        search_directive = None
        show_related_directive = None
        aggregations = []
        chart = None

        for d in story.directives:
            if isinstance(d, ShowPage):
                page_name = d.page_name
            elif isinstance(d, DisplayTable):
                display_table = d
            elif isinstance(d, AcceptInput):
                accept_input = d
            elif isinstance(d, AllowFilter):
                filters_directive = d
            elif isinstance(d, AllowSearch):
                search_directive = d
            elif isinstance(d, ShowRelated):
                show_related_directive = d
            elif isinstance(d, DisplayAggregation):
                aggregations.append(d)
            elif isinstance(d, ShowChart):
                chart = d

        if not page_name:
            return

        slug = _snake(page_name)
        var_name = f"TEMPLATE_{slug.upper()}"

        # GET route for the page
        self._w(f'@app.get("/{slug}", response_class=HTMLResponse)')
        self._w(f"async def page_{slug}(request: Request):")
        self._w(f'    user = get_current_user(request)')
        self._w(f'    q = request.query_params.get("q", "")')
        self._w(f'    db = await get_db()')
        self._w(f'    try:')
        self._w(f'        context = {{')
        self._w(f'            "page_title": "{page_name}",')
        self._w(f'            "current_role": user["role"],')
        self._w(f'            "roles": list(ROLES.keys()),')
        self._w(f'            "q": q,')
        self._w(f'        }}')

        if display_table:
            table = _table(display_table.content_name)
            self._w(f'        query = "SELECT * FROM {table}"')
            self._w(f'        params = []')
            self._w(f'        conditions = []')

            # Filter support
            if filters_directive:
                for f in filters_directive.fields:
                    fname = _snake(f)
                    self._w(f'        {fname}_val = request.query_params.get("{fname}", "")')
                    self._w(f'        if {fname}_val:')
                    self._w(f'            conditions.append("{fname} = ?")')
                    self._w(f'            params.append({fname}_val)')

            # Search support
            if search_directive:
                search_cols = [_snake(f) for f in search_directive.fields]
                or_clauses = " OR ".join(f"{c} LIKE ?" for c in search_cols)
                self._w(f'        if q:')
                self._w(f'            conditions.append("({or_clauses})")')
                for _ in search_cols:
                    self._w(f'            params.append(f"%{{q}}%")')

            self._w(f'        if conditions:')
            self._w(f'            query += " WHERE " + " AND ".join(conditions)')
            self._w(f'        cursor = await db.execute(query, params)')
            self._w(f'        rows = await cursor.fetchall()')
            self._w(f'        context["items"] = [dict(r) for r in rows]')
            self._w(f'        context["filters"] = dict(request.query_params)')

            # Populate warehouse_options from distinct values if warehouse filter exists
            if filters_directive and "warehouse" in [_snake(f) for f in filters_directive.fields]:
                self._w(f'        wh_cursor = await db.execute("SELECT DISTINCT warehouse FROM stock_levels ORDER BY warehouse")')
                self._w(f'        context["warehouse_options"] = [r["warehouse"] for r in await wh_cursor.fetchall()]')

            # Show related: for each item, fetch related content
            if show_related_directive:
                related_table = _table(show_related_directive.related_content)
                group_col = _snake(show_related_directive.group_by)
                self._w(f'        for item in context["items"]:')
                self._w(f'            rcursor = await db.execute("SELECT * FROM {related_table} WHERE product = ?", (item["id"],))')
                self._w(f'            related_rows = [dict(r) for r in await rcursor.fetchall()]')
                self._w(f'            item["related"] = ", ".join(str(r.get("{group_col}", "")) + ":" + str(r.get("quantity", "")) for r in related_rows)')

        # Aggregations
        for agg in aggregations:
            slug_agg = _snake(agg.description)[:30]
            if "count" in agg.description.lower():
                # Figure out which content to count
                content_guess = self._guess_content_from_text(agg.description)
                if content_guess:
                    tbl = _table(content_guess)
                    if "active" in agg.description.lower() or "breakdown" in agg.description.lower():
                        self._w(f'        cursor_agg = await db.execute("SELECT COUNT(*) as total, status FROM {tbl} GROUP BY status")')
                        self._w(f'        agg_rows = await cursor_agg.fetchall()')
                        self._w("        agg_rows = [dict(r) for r in agg_rows]")
                        self._w("        breakdown_parts = [str(r['status']) + ': ' + str(r['total']) for r in agg_rows]")
                        self._w("        breakdown = ', '.join(breakdown_parts)")
                        self._w("        total = sum(r['total'] for r in agg_rows)")
                        self._w('        context["' + slug_agg + '"] = str(total) + " (" + breakdown + ")"')
                    else:
                        self._w(f'        cursor_agg = await db.execute("SELECT COUNT(*) as cnt FROM {tbl}")')
                        self._w(f'        context["{slug_agg}"] = (await cursor_agg.fetchone())["cnt"]')
            elif "sum" in agg.description.lower() or "value" in agg.description.lower():
                self._w(f'        cursor_agg = await db.execute("SELECT COALESCE(SUM(sl.quantity * p.unit_cost), 0) as val FROM stock_levels sl JOIN products p ON sl.product = p.id")')
                self._w("        val = (await cursor_agg.fetchone())['val']")
                self._w('        context["' + slug_agg + '"] = f"${val:.2f}"')

        # Nav badges
        if self.p.navigation:
            for item in self.p.navigation.items:
                if item.badge:
                    badge_slug = _snake(item.label)
                    if "alert" in item.badge.lower() and "count" in item.badge.lower():
                        self._w(f'        cursor_badge = await db.execute("SELECT COUNT(*) as cnt FROM reorder_alerts")')
                        self._w(f'        context["badge_{badge_slug}"] = (await cursor_badge.fetchone())["cnt"]')

        # Chart data endpoint
        if chart:
            chart_table = _table(chart.content_name)
            self._w(f'        # Chart data is fetched via separate API endpoint')

        # Fetch reference lists for form dropdowns + existing records for CRUD table
        if accept_input:
            content_obj = self._find_content_for_fields(accept_input.fields)
            if content_obj:
                form_table = _table(content_obj.name)
                for fname in accept_input.fields:
                    col = _snake(fname)
                    field_obj = next((f for f in content_obj.fields if _snake(f.name) == col), None)
                    if field_obj and field_obj.type_expr.references:
                        ref_table = _table(field_obj.type_expr.references)
                        self._w(f'        ref_cursor = await db.execute("SELECT * FROM {ref_table}")')
                        self._w(f'        context["{ref_table}_list"] = [dict(r) for r in await ref_cursor.fetchall()]')

                # Fetch existing records for the auto-generated CRUD table
                has_explicit_table = any(isinstance(dir_, DisplayTable) for dir_ in story.directives)
                if not has_explicit_table:
                    self._w(f'        rows_cursor = await db.execute("SELECT * FROM {form_table} ORDER BY id DESC")')
                    self._w(f'        context["{form_table}_rows"] = [dict(r) for r in await rows_cursor.fetchall()]')

        self._w(f'        content_html = {var_name}.render(**context)')
        self._w(f'        return BASE_TEMPLATE.render(content=content_html, **context)')
        self._w(f'    finally:')
        self._w(f'        await db.close()')
        self._w()

        # POST route for form pages
        if accept_input:
            self._emit_form_post_route(story, accept_input, slug)

    def _emit_form_post_route(self, story, accept_input, slug):
        # Find the content this form creates (best match by field count)
        content_obj = self._find_content_for_fields(accept_input.fields)

        if not content_obj:
            return

        table = _table(content_obj.name)
        create_scope = self._create_scope(content_obj.name)
        scope_dep = f', user=Depends(require_scope("{create_scope}"))' if create_scope else ""

        # Determine initial state (only if content has a state machine)
        initial_state = None
        validate_field = None
        has_state_machine = content_obj.name in self._state_machines
        for d in story.directives:
            if isinstance(d, CreateAs) and has_state_machine:
                initial_state = d.initial_state
            elif isinstance(d, ValidateUnique):
                validate_field = d.field

        form_params = []
        for fname in accept_input.fields:
            col = _snake(fname)
            form_params.append(f'{col}: str = Form("")')

        params_str = ", ".join(form_params)

        self._w(f'@app.post("/{slug}", response_class=HTMLResponse)')
        self._w(f"async def page_{slug}_post(request: Request, edit_id: str = Form(\"\"), {params_str}{scope_dep}):")
        self._w(f'    db = await get_db()')
        self._w(f'    try:')

        # Cast form string values to proper types
        for fname in accept_input.fields:
            col = _snake(fname)
            field_obj = next((f for f in content_obj.fields if _snake(f.name) == col), None)
            if field_obj and field_obj.type_expr.base_type in ("whole_number", "reference"):
                self._w(f'        {col} = int({col}) if {col} else None')
            elif field_obj and field_obj.type_expr.base_type == "currency":
                self._w(f'        {col} = float({col}) if {col} else None')

        self._w(f'        if edit_id:')
        # UPDATE path
        update_cols = [_snake(f) for f in accept_input.fields]
        set_clause = ", ".join(f'{c} = ?' for c in update_cols)
        values_list_update = [_snake(f) for f in accept_input.fields]
        values_str_update = ", ".join(values_list_update)
        self._w(f'            await db.execute(')
        self._w(f'                "UPDATE {table} SET {set_clause} WHERE id = ?",')
        self._w(f'                ({values_str_update}, int(edit_id),)')
        self._w(f'            )')
        self._w(f'        else:')

        # INSERT path
        insert_cols = [_snake(f) for f in accept_input.fields]
        if initial_state:
            insert_cols.append("status")
        cols_sql = ", ".join(insert_cols)
        placeholders = ", ".join(["?"] * len(insert_cols))
        values_list = [_snake(f) for f in accept_input.fields]
        if initial_state:
            values_list.append(f'"{initial_state}"')
        values_str = ", ".join(values_list)

        # Uniqueness validation (only on insert)
        if validate_field:
            vcol = _snake(validate_field)
            self._w(f'            cursor = await db.execute("SELECT id FROM {table} WHERE {vcol} = ?", ({vcol},))')
            self._w(f'            if await cursor.fetchone():')
            self._w(f'                raise HTTPException(status_code=422, detail="{validate_field} already exists")')

        self._w(f'            await db.execute(')
        self._w(f'                "INSERT INTO {table} ({cols_sql}) VALUES ({placeholders})",')
        self._w(f'                ({values_str},)')
        self._w(f'            )')
        self._w(f'        await db.commit()')
        self._w(f'        return RedirectResponse(url="/{slug}", status_code=303)')
        self._w(f'    finally:')
        self._w(f'        await db.close()')
        self._w()

        # DELETE route for this form page
        has_display_table = any(isinstance(dir_, DisplayTable) for dir_ in story.directives)
        if not has_display_table:
            delete_scope = self._delete_scope(content_obj.name)
            update_scope = self._update_scope(content_obj.name)
            # Use the most permissive scope available (update or delete)
            del_scope = delete_scope or update_scope or create_scope
            del_scope_dep = f', user=Depends(require_scope("{del_scope}"))' if del_scope else ""
            self._w(f'@app.post("/{slug}/delete/{{record_id}}", response_class=HTMLResponse)')
            self._w(f"async def page_{slug}_delete(record_id: int{del_scope_dep}):")
            self._w(f'    db = await get_db()')
            self._w(f'    try:')
            self._w(f'        await db.execute("DELETE FROM {table} WHERE id = ?", (record_id,))')
            self._w(f'        await db.commit()')
            self._w(f'        return RedirectResponse(url="/{slug}", status_code=303)')
            self._w(f'    finally:')
            self._w(f'        await db.close()')
            self._w()

    def _find_content_for_fields(self, field_names: list[str]):
        """Find the Content object that best matches the given field names."""
        best = None
        best_count = 0
        for c in self.p.contents:
            count = sum(1 for f in field_names if _snake(f) in {_snake(cf.name) for cf in c.fields})
            if count > best_count:
                best_count = count
                best = c
        return best

    def _guess_content_from_text(self, text: str) -> Optional[str]:
        text_lower = text.lower()
        for c in self.p.contents:
            if c.name.lower() in text_lower or c.singular.lower() in text_lower:
                return c.name
        return None

    # ── Chart data API ──

    def _emit_chart_data_routes(self) -> None:
        for story in self.p.stories:
            for d in story.directives:
                if isinstance(d, ShowChart):
                    table = _table(d.content_name)
                    self._w(f'@app.get("/api/chart-data/{table}")')
                    self._w(f"async def chart_data_{table}():")
                    self._w(f'    db = await get_db()')
                    self._w(f'    try:')
                    sql = (f"SELECT DATE(created_at) as day, COUNT(*) as cnt "
                           f"FROM {table} "
                           f"WHERE created_at >= DATE('now', '-{d.days} days') "
                           f"GROUP BY DATE(created_at) ORDER BY day")
                    self._w(f'        cursor = await db.execute("{sql}")')
                    self._w(f'        rows = await cursor.fetchall()')
                    self._w(f'        return {{"labels": [dict(r)["day"] for r in rows], "values": [dict(r)["cnt"] for r in rows]}}')
                    self._w(f'    finally:')
                    self._w(f'        await db.close()')
                    self._w()

    # ── Startup ──

    def _emit_startup(self) -> None:
        self._emit_chart_data_routes()

    # ── Main ──

    def _emit_main(self) -> None:
        self._wblock('''\
            if __name__ == "__main__":
                import argparse
                parser = argparse.ArgumentParser(description="{app_name}")
                parser.add_argument("--port", "-p", type=int, default=8000, help="Port to listen on (default: 8000)")
                parser.add_argument("--host", default="0.0.0.0", help="Host to bind to (default: 0.0.0.0)")
                args = parser.parse_args()
                uvicorn.run(app, host=args.host, port=args.port)
        '''.format(app_name=self.p.application.name if self.p.application else "an AWS-native Termin runtime App"))


def generate(program: Program, source_file: str = "unknown.an AWS-native runtime") -> str:
    """Generate a complete Python application from a validated Program AST."""
    gen = CodeGenerator(program, source_file)
    return gen.generate()
